### ISSUE TITLE
Scalar operations over dataframe - Inconsistent results

### ISSUE THREAD

**Issue by telson** [pydata/pandas#11621] opened 2015-11-17 01:10 UTC
Converting percentages to multipliers on this dataframe produces interesting results (in that its occasionally wrong).

```python
In [1]: df = pd.read_hdf(r'pct_change.h5', 'data')

In [2]: df.head()
Out[2]:
            T0  T1  T2      T3  T4  T5  ...    T1194  T1195  T1196  T1197  T1198  T1199
date                                    ...
2006-05-19 NaN NaN NaN     NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-22 NaN NaN NaN -0.0613 NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-23 NaN NaN NaN -3.9288 NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-24 NaN NaN NaN     NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-25 NaN NaN NaN     NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN

[5 rows x 1200 columns]

In [3]: #((sign * df / 100.0) + 1.0).head()

In [4]: sign = -1

In [5]: sign = -1.0

In [6]: ((sign * df / 100.0) + 1.0).head()
Out[6]:
            T0  T1  T2        T3  T4  T5  ...    T1194  T1195  T1196  T1197  T1198  T1199
date                                      ...
2006-05-19 NaN NaN NaN       NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-22 NaN NaN NaN  1.000613 NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-23 NaN NaN NaN  1.039288 NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-24 NaN NaN NaN       NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-25 NaN NaN NaN       NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN

[5 rows x 1200 columns]
```
... 16 tries later ...

```python
In [22]: ((sign * df / 100.0) + 1.0).head()
Out[22]:
            T0  T1  T2        T3  T4  T5  ...    T1194  T1195  T1196  T1197  T1198  T1199
date                                      ...
2006-05-19 NaN NaN NaN       NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-22 NaN NaN NaN  1.000613 NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-23 NaN NaN NaN  1.039288 NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-24 NaN NaN NaN       NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-25 NaN NaN NaN       NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN

[5 rows x 1200 columns]

In [23]: ((sign * df / 100.0) + 1.0).head()
Out[23]:
            T0  T1  T2        T3  T4  T5  ...    T1194  T1195  T1196  T1197  T1198  T1199
date                                      ...
2006-05-19 NaN NaN NaN       NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-22 NaN NaN NaN  1.000613 NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-23 NaN NaN NaN  1.039288 NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-24 NaN NaN NaN       NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-25 NaN NaN NaN       NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN

[5 rows x 1200 columns]

In [24]: ((sign * df / 100.0) + 1.0).head()
Out[24]:
            T0  T1  T2  T3  T4  T5  ...    T1194  T1195  T1196  T1197  T1198  T1199
date                                ...
2006-05-19   0   0   0   0   0   0  ...        0      0      0      0      0      0
2006-05-22   0   0   0   0   0   0  ...        0      0      0      0      0      0
2006-05-23   0   0   0   0   0   0  ...        0      0      0      0      0      0
2006-05-24   0   0   0   0   0   0  ...        0      0      0      0      0      0
2006-05-25   0   0   0   0   0   0  ...        0      0      0      0      0      0

[5 rows x 1200 columns]

In [25]: ((sign * df / 100.0) + 1.0).head()
Out[25]:
            T0  T1  T2        T3  T4  T5  ...    T1194  T1195  T1196  T1197  T1198  T1199
date                                      ...
2006-05-19 NaN NaN NaN       NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-22 NaN NaN NaN  1.000613 NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-23 NaN NaN NaN  1.039288 NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-24 NaN NaN NaN       NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN
2006-05-25 NaN NaN NaN       NaN NaN NaN  ...      NaN    NaN    NaN    NaN    NaN    NaN

[5 rows x 1200 columns]

In [26]: ((sign * df / 100.0) + 1.0).head()
Out[26]:
            T0  T1  T2  T3  T4  T5  ...    T1194  T1195  T1196  T1197  T1198  T1199
date                                ...
2006-05-19   1   1   1   1   1   1  ...        1      1      1      1      1      1
2006-05-22   1   1   1   1   1   1  ...        1      1      1      1      1      1
2006-05-23   1   1   1   1   1   1  ...        1      1      1      1      1      1
2006-05-24   1   1   1   1   1   1  ...        1      1      1      1      1      1
2006-05-25   1   1   1   1   1   1  ...        1      1      1      1      1      1

[5 rows x 1200 columns]

In [27]: ((sign * df / 100.0) + 1.0).head()
```

#### System:
- Windows 8.1 Pro

```bash
> conda list | grep pandas
pandas                    0.16.2               np19py34_0
> conda list | grep python
ipython                   4.0.0                    py34_0
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py34_0
python                    3.4.3                         4
python-dateutil           2.4.2                    py34_0
> conda update pandas
Fetching package metadata: ....
Solving package specifications: ............
Package plan for installation in environment C:\LocalSoftware\miniconda\envs\general:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pytz-2015.7                |           py34_0         167 KB
    pandas-0.17.0              |      np110py34_0         5.8 MB
    ------------------------------------------------------------
                                           Total:         6.0 MB

Th

e following packages will be UPDATED:

    pandas: 0.16.2-np19py34_0 --> 0.17.0-np110py34_0
    pytz:   2015.6-py34_0     --> 2015.7-py34_0
```

Post update - same behavior
Data: https://github.com/telson/pandasbugdata

**Comment by jreback** [comment] 2015-11-17 14:50
dupe of this issue: https://github.com/pydata/pandas/issues/11629

**Closed by jreback** 2015-11-17 14:50 UTC
