### ISSUE TITLE
0.17 drop_duplicates() incorrectly dropping non-unique values

### ISSUE THREAD

**Issue by amanhanda** [pydata/pandas#11459] opened 2015-10-28 16:55 UTC
Under 0.17, numpy 1.10

```
In [32]: import pandas

In [33]: df = pandas.DataFrame(data={"a" : [0, 1, 3, 4], "b":[20, 16, 8, 4]})

In [34]: df
Out[34]:
   a   b
0  0  20
1  1  16
2  3   8
3  4   4

In [35]: df.drop_duplicates(['a','b'], keep='last')
Out[35]:
   a  b
3  4  4
```
0.16.2 has the correct behavior.

```
In [6]: import pandas

In [7]: df = pandas.DataFrame(data={"a" : [0, 1, 3, 4], "b":[20, 16, 8, 4]})

In [8]: df
Out[8]:
   a   b
0  0  20
1  1  16
2  3   8
3  4   4

In [9]: df.drop_duplicates(['a','b'])
Out[9]:
   a   b
0  0  20
1  1  16
2  3   8
3  4   4
```

**Comment by jreback** [comment] 2015-10-28 16:56
thanks for the report, a dupe of: https://github.com/pydata/pandas/issues/11376

this was already fixed here: https://github.com/pydata/pandas/pull/11403

and will be in forthcoming 0.17.1 (it's in master now)

**Closed by jreback** 2015-10-28 16:56 UTC
