### ISSUE TITLE
drop_duplicates() is dropping more than just duplicates in 0.17.0

### ISSUE THREAD

**Issue by andersonjacob** [pydata/pandas#11512] opened 2015-11-03 18:17 UTC
When I upgraded from 0.16.2 to 0.17.0, I was met with a nasty surprise when dropping duplicates.  It looks like DataFrame.drop_duplicates() is not working as I would expect it to based on the previous version.  I have a dataframe

```
test_ids = df['test_id'].unique()
print('N test ids: {}'.format(test_ids.shape))
print('N tests: {}'.format(df[['test_id', <some other columns>]].drop_duplicates().shape))
```
the output is:
```
N test ids: (341334,)
N tests: (237426, 10)
```
when I run the same in 0.16.2 the output is:
```
N test ids: (341334,)
N tests: (341334, 10)
```

I don't think you should be able to get fewer rows than the number of unique entries in a single column.

**Comment by TomAugspurger** [comment] 2015-11-03 18:48
Sorry about that.

Probably a dupe of https://github.com/pydata/pandas/issues/11376, fixed in https://github.com/pydata/pandas/pull/11403 which is in master.

If you're able could you build master and see if it's fixed for you? Thanks.

**Closed by TomAugspurger** 2015-11-03 18:48 UTC
