### ISSUE TITLE
describe() doesn't ignore Nan anymore

### ISSUE THREAD

**Issue by rubennj** [pydata/pandas#13387] opened 2016-06-07 16:49 UTC
`.describe()` is not ignoring the `Nan` values at percentiles, so it gives `Nan`:

http://pandas.pydata.org/pandas-docs/stable/basics.html#summarizing-data-describe

Before 0.18 it was working as expected:

http://pandas.pydata.org/pandas-docs/version/0.17.0/basics.html#summarizing-data-describe

**Comment by jreback** [comment] 2016-06-07 16:51
dupe of https://github.com/pydata/pandas/issues/13098

fixed already by #13122 which will be in 0.18.2

**Closed by jreback** 2016-06-07 16:51 UTC
