### ISSUE TITLE
UTF-8 and read_csv: addressing data frame columns gives KeyError

### ISSUE THREAD

**Issue by Puggie** [pydata/pandas#6563] opened 2014-03-06 11:08 UTC
When reading a csv, generated by Microsoft SQL Server management studio in UTF-8 encoding by following line of code:

    df = pd.read_csv(file.csv)

gives problems when specific data frame columns are addressed.

Reading the csv itself doesn't give any problem or warning. And it is possible to view the data frame (showing the proper header names). But when you want to address a specific column by its header name, the following error occurs:

KeyError: 'no item named *header name*'

When opening the file with a text editor and saving it in ANSI format, the issue isn't there anymore. This workflow helped to overcome this issue by accident, since I was not aware of any encoding issues at all.

It would be a big time saver for a user when he is made aware of possible encoding issues at the moment of reading a file. If a column is shown properly and when you address this column by its name resulting in a KeyError is confusing and not helpful.

**Comment by jreback** [comment] 2015-03-08 16:38
closing as not a bug

**Closed by jreback** 2015-03-08 16:38 UTC
Labels: CSV
