### ISSUE TITLE
DataFrame.describe can't return percentiles when data set contain nan 

### ISSUE THREAD

**Issue by tade0726** [pydata/pandas#13118] opened 2016-05-09 08:09 UTC
#### Code Sample, a copy-pastable example if possible

des_table = df_final_S1415.describe(percentiles=[.05, .25, .5, .75, .95 ]).T

#### Expected Output
In version 18.0 describe function will return percentiles when columns contain nan. 

#### output of ``pd.show_versions()``

But in version 18.1 describe function will not  return percentiles when columns contain nan.

**Comment by jorisvandenbossche** [comment] 2016-05-09 09:30
@tade0726 Can you please show a reproducible example? (some code that constructs a dataframe that shows the problem)

**Comment by jorisvandenbossche** [comment] 2016-05-09 09:36
Here is a reproducible example (the actual issue is in the `quantile` method):

```
In [24]: s = pd.Series(range(5))

In [25]: s.quantile(0.5)
Out[25]: 2.0

In [26]: s[0] = np.nan

In [27]: s.quantile(0.5)
Out[27]: nan

In [28]: pd.__version__
Out[28]: '0.18.1+20.gaf7bdd3'
```

**Comment by jorisvandenbossche** [comment] 2016-05-09 09:37
And it is a duplicate of https://github.com/pydata/pandas/issues/13098

Thanks for reporting

**Closed by jorisvandenbossche** 2016-05-09 09:37 UTC
Labels: Needs Info
