### ISSUE TITLE
read_csv character encoding bug?

### ISSUE THREAD

**Issue by hayd** [pydata/pandas#2741] opened 2013-01-23 21:45 UTC
This is a weird one from [StackOverflow](http://stackoverflow.com/questions/14488697/pandas-read-csv-failing-on-columns-with-null-characters), this file has some `\x00`s which seem to be ignored when printing but confuse `read_csv`:

```
x = 'x,y\n \x00\x00\x00,Reg\n \x00\x00\x00,Reg\nI,Swp\nI,Swp\n'
X = StringIO(x)

In [3]: pd.read_csv(X)
Out[3]: 
     x    y
0          
1  NaN  NaN
2    I  Swp
3    I  Swp

In [4]: print x
x,y
 ,Reg
 ,Reg
I,Swp
I,Swp
```

**Comment by msiler** [comment] 2016-01-14 16:13
I know this is an old issue, but I'd like to give it a little bump. I have customers giving us a dump of some of their production database tables. The files we are getting are tab delimited and values that were null in the database are null bytes in the text file. I don't know how to get pandas to read this without having to do some manual munging first.

**Comment by wesm** [comment] 2016-01-14 21:27
I'm sorry this never got fixed! I have also seen null bytes used to code nulls. @jreback @jorisvandenbossche let's slate this for 0.18?

**Comment by wesm** [comment] 2016-01-14 21:42
I'd like to make some changes to the CSV tokenizer to hopefully improve its performance, that will also allow us to get rid of the null terminators that are complicating issues like this, but it would make most sense to understand for 1.0 / libpandas. Question is whether there is a quick fix for this particular issue with the existing tokenization strategy

**Comment by gfyoung** [comment] 2016-07-31 17:45
I don't believe this is an issue with the C engine anymore:
~~~python
>>> from pandas.compat import StringIO
>>> from pandas import read_csv
>>> data = 'x,y\n \x00\x00\x00,Reg\n \x00\x00\x00,Reg\nI,Swp\nI,Swp\n'
>>> read_csv(StringIO(data), engine='c')
     x    y
0  NaN  Reg
1  NaN  Reg
2    I  Swp
3    I  Swp
~~~
Unfortunately, as @wesm pointed out <a href="https://github.com/pydata/pandas/issues/2741#issuecomment-15628473">here</a>, it will fail for the Python engine:
~~~python
>>> read_csv(StringIO(data), engine='python')
...
_csv.Error: line contains NULL byte
~~~
This issue however, seems beyond our control, so I'm not sure if we should still classify this as a BUG on the `pandas` end if the issue is originating in Python's `csv` module.

**Comment by jreback** [comment] 2016-07-31 18:33
if u want to put up tests for the c engine and s nice error message Python engine then can close

**Comment by wesm** [comment] 2016-08-01 18:09
Relatedly: what is the current implementation gap between the C and pure Python CSV parsers?

**Comment by gfyoung** [comment] 2016-08-01 18:34
@wesm: We have a list of known differences in #12686.  That alone indicates a pretty noticeable gap.

**Comment by wesm** [comment] 2016-08-01 19:19
Seems like if you can address the regex delimiter problem (easier said than done) then it may be possible to deprecate the Python engine. This would be easier in the possible pandas 2.0 future in which we might add libre2 to the build / development toolchain

**Closed** 2016-08-01 21:17 UTC
Labels: Bug, Data IO, Difficulty Intermediate, Effort Low
