### ISSUE TITLE
Uncompatibility of pandas.read_pickle with pytz

### ISSUE THREAD

**Issue by AndrewUshakov** [pydata/pandas#6871] opened 2014-04-11 13:22 UTC
Test program below:
```python
import datetime, pytz, pandas

pandas.show_versions()

dates = [datetime.datetime(2014,1,1,1,1, tzinfo=pytz.utc),
         datetime.datetime(2014,2,2,2,2, tzinfo=pytz.utc),
         datetime.datetime(2014,3,3,3,3, tzinfo=pytz.utc)]

s = pandas.Series(dates)
s.to_pickle('series.pickle')

# import pickle
# with open('series.pickle', 'rb') as f: s1 = pickle.load(f)

s2 = pandas.read_pickle('series.pickle')
```
crashes at the last line with long stack trace. If replace "pytz.utc" by "datetime.timezone.utc", error disappears. Commented code fragment works properly in both cases.
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.0.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 26 Stepping 5, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.13.1
Cython: None
numpy: 1.8.1
scipy: 0.13.3
statsmodels: 0.5.0
IPython: None
sphinx: 1.2.2
patsy: 0.2.1
scikits.timeseries: None
dateutil: 2.2
pytz: 2014.2
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.3.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
sqlalchemy: 0.9.4
lxml: 3.3.4
bs4: 4.3.2
html5lib: 0.999
bq: None
apiclient: None
Traceback (most recent call last):
  File "C:\Program Files\Python34\lib\site-packages\pandas\io\pickle.py", line 43, in try_read
    return pc.load(fh, encoding=encoding, compat=False)
  File "C:\Program Files\Python34\lib\site-packages\pandas\compat\pickle_compat.py", line 89, in load
    return up.load()
  File "C:\Program Files\Python34\lib\pickle.py", line 1036, in load
    dispatch[key[0]](self)
  File "C:\Program Files\Python34\lib\site-packages\pandas\compat\pickle_compat.py", line 18, in load_reduce
    if type(args[0]) is type:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python34\lib\site-packages\pandas\io\pickle.py", line 49, in read_pickle
    return try_read(path)
  File "C:\Program Files\Python34\lib\site-packages\pandas\io\pickle.py", line 46, in try_read
    return pc.load(fh, encoding=encoding, compat=True)
  File "C:\Program Files\Python34\lib\site-packages\pandas\compat\pickle_compat.py", line 89, in load
    return up.load()
  File "C:\Program Files\Python34\lib\pickle.py", line 1036, in load
    dispatch[key[0]](self)
  File "C:\Program Files\Python34\lib\pickle.py", line 1316, in load_newobj_ex
    obj = cls.__new__(cls, *args, **kwargs)
TypeError: Required argument 'shape' (pos 1) not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python34\lib\site-packages\pandas\io\pickle.py", line 43, in try_read
    return pc.load(fh, encoding=encoding, compat=False)
  File "C:\Program Files\Python34\lib\site-packages\pandas\compat\pickle_compat.py", line 89, in load
    return up.load()
  File "C:\Program Files\Python34\lib\pickle.py", line 1036, in load
    dispatch[key[0]](self)
  File "C:\Program Files\Python34\lib\site-packages\pandas\compat\pickle_compat.py", line 18, in load_reduce
    if type(args[0]) is type:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:/My Documents/PyCharm/LFDM/CalcFlowRate/tpicle.py", line 17, in <module>
    s2 = pandas.read_pickle('series.pickle')
  File "C:\Program Files\Python34\lib\site-packages\pandas\io\pickle.py", line 52, in read_pickle
    return try_read(path, encoding='latin1')
  File "C:\Program Files\Python34\lib\site-packages\pandas\io\pickle.py", line 46, in try_read
    return pc.load(fh, encoding=encoding, compat=True)
  File "C:\Program Files\Python34\lib\site-packages\pandas\compat\pickle_compat.py", line 89, in load
    return up.load()
  File "C:\Program Files\Python34\lib\pickle.py", line 1036, in load
    dispatch[key[0]](self)
  File "C:\Program Files\Python34\lib\pickle.py", line 1316, in load_newobj_ex
    obj = cls.__new__(cls, *args, **kwargs)
TypeError: Required argument 'shape' (pos 1) not found

Process finished with exit code 1
```
---
Best regards,
Andrew

**Comment by lssilva** [comment] 2015-02-08 15:59
Same problem here

**Comment by jreback** [comment] 2015-02-08 16:03
try in 0.15.2 and master

**Comment by akaihola** [comment] 2016-01-28 07:58
We have this problem when writing pickles with Pandas 0.14.1 and reading them with Pandas 0.17.1. The problem occurs if the pickles contain `isodate.UTC` objects.

The problem can be reduced to this test case:

**my_tz.py**:

    from datetime import tzinfo

    class MyTz(tzinfo):
        def __init__(self):
            pass

**write_pickle.py** (run with Pandas 0.14.1):

    import pandas as pd
    import cPickle
    from my_tz import MyTz

    data = pd.Series(), MyTz()
    with open('test.pickle', 'wb') as f:
        cPickle.dump(data, f)

**read_pickle.py** (run with Pandas 0.17.1):

    import pandas as pd
    pd.read_pickle('test.pickle')

Reading the pickle with `cPickle.load()` works fine, but with `pd.read_pickle()` we get:

    $ python read_pickle.py
    Traceback (most recent call last):
      File "read_pickle_test.py", line 2, in <module>
        pd.read_pickle('test.pickle')
      File "pandas/io/pickle.py", line 60, in read_pickle
        return try_read(path)
      File "pandas/io/pickle.py", line 57, in try_read
        return pc.load(fh, encoding=encoding, compat=True)
      File "pandas/compat/pickle_compat.py", line 116, in load
        return up.load()
      File "/usr/lib64/python2.7/pickle.py", line 858, in load
        dispatch[key](self)
      File "pandas/compat/pickle_compat.py", line 16, in load_reduce
        if type(args[0]) is type:
    IndexError: tuple index out of range

I see the following problems in [pandas.compat.pickle_compat.load_reduce()](/pydata/pandas/blob/9bc82438268742575e501d099c6f22ce0a2dcac1/pandas/compat/pickle_compat.py#L13):

(1) It attemps to access `args[0]` while `args` can be empty.

    if type(args[0]) is type:
        n = args[0].__name__

(2) The above code is dead code anyway, since `n` isn't referenced to anywhere else in the function. Removing those two lines fixes the unpickling problem completely.

Note that the `MyTz` class in the test above does implement a proper `__init__()` method as required in [Python documentation for tzinfo](https://docs.python.org/2.7/library/datetime.html#tzinfo-objects): *"Special requirement for pickling: A tzinfo subclass must have an `__init__` method that can be called with no arguments, else it can be pickled but possibly not unpickled again. This is a technical requirement that may be relaxed in the future."* While `isodate.UTC` violates this requirement, that doesn't seem to be the cause of this problem.

(3) Also, at the very end of `load_reduce()`:

    stack[-1] = value

is code that is never reached, since all previous code branches either return or raise. Also, this line is invalid, since `value` isn't initialized anywhere in the function.

**Comment by gfyoung** [comment] 2016-07-26 04:34
@jreback : can't reproduce this anymore:
~~~python
...  # run the code above
>>> import pandas.util.testing as tm
>>> tm.assert_series_equal(s, s2)
>>>
~~~

**Comment by sinhrks** [comment] 2016-07-26 07:05
yeah it should be supported by ``DatetimeTZDtype`` and tested. Closing.

- https://github.com/pydata/pandas/blob/master/pandas/io/tests/generate_legacy_storage_files.py#L98

**Closed by sinhrks** 2016-07-26 07:05 UTC
Labels: Bug, Compat

**Comment by saitam1** [comment] 2017-07-01 11:03
So how to fix this?
When I do 
`pd.read_pickle('buyapple.pickle')`
I get 
`IndexError: tuple index out of range`

**Comment by jreback** [comment] 2017-07-01 11:25
this was fixed quite a long time ago

you would have to show a reproducible example

**Comment by saitam1** [comment] 2017-07-04 13:50
I am using [this ](http://www.zipline.io/beginner-tutorial.html#running-the-algorithm)zipline example, which creates a pickle file as follows:
`zipline run -f ../../zipline/examples/buyapple.py --start 2000-1-1 --end 2014-1-1 -o buyapple_out.pickle
`
Then I try to read the pickle file:
```
import pandas as pd
perf = pd.read_pickle('buyapple_out.pickle')
```
which gives me an error:
`IndexError: tuple index out of range
`

**Comment by jreback** [comment] 2017-07-04 15:12
@saitam1 you would have to show a pure pandas example, otherwise you should report this to zipline.
