### ISSUE TITLE
Reindex MultiIndex of type float 

### ISSUE THREAD

**Issue by leroygr** [pydata/pandas#10169] opened 2015-05-19 11:14 UTC
Hi,

There is a strange behavior when I want to reindex a Multi-Index (float64) of a Series: some of the original values are dropped from the reindexed object.

Here is the test case:

```python
>>> import pandas as pd
>>> import numpy as np

>>> df_g=pd.Series(index=pd.MultiIndex.from_tuples([(10.,4.2),(11.,5.2),(14,7.8)]),data=[0.01,0.2,0.684])
10  4.2    0.010
11  5.2    0.200
14  7.8    0.684
dtype: float64

>>> df_g_r=pd.Series(index=pd.MultiIndex.from_product([np.arange(0,360,1.),np.arange(0,25,0.1)])).fillna(0)

>>> df_g.reindex(df_g_r.index).dropna()
10  4.2    0.01
11  5.2    0.20
dtype: float64

```

Anyone has an idea of what is going on? Is there any workaround for this?

Many thanks,
Greg

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-51-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.15.2
nose: 1.3.4
Cython: 0.21.2
numpy: 1.8.2
scipy: 0.15.1
statsmodels: None
IPython: 2.3.1
sphinx: 1.2.2
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.4
bottleneck: 0.8.0
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.4.2
openpyxl: 1.8.6
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: None
lxml: 3.3.3
bs4: None
html5lib: None
httplib2: 0.8
apiclient: None
rpy2: None
sqlalchemy: 0.9.8
pymysql: 0.6.6.None
psycopg2: None

**Comment by leroygr** [comment] 2015-05-19 13:40
FYI, I managed to solve the issue by using np.around when building the df_f_r object:
```python
>>> df_g_r=pd.Series(index=pd.MultiIndex.from_product([np.around(np.arange(0,360,1.),decimals=5),np.around(np.arange(0,25,0.1),decimals=5)])).fillna(0)
>>> df_g.reindex(df_g_r.index).dropna()
10  4.2    0.010
11  5.2    0.200
14  7.8    0.684
dtype: float64
```

**Comment by shoyer** [comment] 2015-05-19 17:12
This is a floating point precision issue. See https://github.com/pydata/pandas/issues/9817

**Comment by jreback** [comment] 2015-05-20 10:55
closing as a dupe of #9817

**Closed by jreback** 2015-05-20 10:55 UTC
Labels: Dtypes, Dupe, Indexing, Reshaping
