### ISSUE TITLE
Add key option to sort methods

### ISSUE THREAD

**Issue by SethMMorton** [pydata/pandas#9855] opened 2015-04-11 18:14 UTC
One feature that I am missing from dataframes is to sort with a custom `key` function, similar to the builtin `sorted` or `list.sort`. I see there is some effort to unify sorting in issue #8239, so it might be a nice to add this powerful functionality to `pandas` while the sorting API is being overhauled.

**Comment by jreback** [comment] 2015-04-11 18:15
pls show an example of what/how this would be used as generally you can simply pass in the column name.

**Comment by jreback** [comment] 2015-04-11 18:16
dupe of #3942 
(you can add an example to that issue)

**Comment by SethMMorton** [comment] 2015-04-11 18:26
I have added the specific example to the dupe.  Thanks!

**Closed** 2015-04-12 13:27 UTC
Labels: Algos, Dupe, Enhancement
