### ISSUE TITLE
multi-character line_terminator in to_csv can improperly convert scientific notation numbers to strings

### ISSUE THREAD

**Issue by lbeltrame** [pydata/pandas#2667] opened 2013-01-09 14:13 UTC
Test case:

````python
In [12]: test = pandas.DataFrame({"A": [1,2,3], "B": [1e-10,4.3434323e-8,3]})

In [13]: test.to_csv("test.txt", sep="\t", line_terminator="\n---\n")

In [14]: cat test.txt
        A       B
---
0       1       "1e-10"
---
1       2       "4.3434322999999997e-08"
---
2       3       3.0
---

````
Notice the quotes around the first two items in "B".

**Comment by gfyoung** [comment] 2016-07-31 21:57
~~~python
>>> from pandas.compat import StringIO
>>> from csv import writer
>>>
>>> buf = StringIO()
>>> w = writer(buf, lineterminator='\n---\n')
>>> w.writerow(['', 'A', 'B'])
9
>>> w.writerow([0, 1, 1e-10])
16
>>> f.seek(0)
0
>>> print(f.read())
,A,B
---
0,1,"1e-10"
---
~~~
This example confirms what @wesm said.  In light of some of the workarounds and the fact that the issue is beyond our control, this issue can be safely closed I think.

**Comment by jreback** [comment] 2016-08-01 10:18
closing as csv module bug. @gfyoung if you are adventurous you might report this as a CPython bug.

**Closed by jreback** 2016-08-01 10:18 UTC
Labels: Bug, Data IO, IO CSV

**Comment by gfyoung** [comment] 2016-08-01 10:45
@jreback : looking at this again, based on the docs <a href="https://docs.python.org/3/library/csv.html#csv.QUOTE_MINIMAL">here</a>, this is intended behaviour:

Because the number `1e-10` contains a `"-"` (which is also in `lineterminator="\n---\n"`), it causes the field to get quoted.  This would explain why any lineterminator <em>without</em> the `"-"` (e.g. `"\nfoo\n"`) did not cause the quoting to occur.
