### ISSUE TITLE
pd.to_datetime giving invalid output

### ISSUE THREAD

**Issue by sumitbinnani** [pydata/pandas#13030] opened 2016-04-29 19:06 UTC
This works:
```
>>> pd.to_datetime(1, unit='D')
Timestamp('1970-01-02 00:00:00')
```

However, the following gives incorrect output:
```
>>> pd.to_datetime(1, unit='D', errors='coerce')
NaT
```

#### Details of Configuration:

python: 2.7.11.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0

**Comment by jorisvandenbossche** [comment] 2016-04-29 19:08
Confirmed with master, thanks for the report!

**Comment by sumitbinnani** [comment] 2016-04-29 19:13
Similarly, this is also not working as desired
```
>>> pd.to_datetime(11111111, unit='D', errors='ignore')
OverflowError: long too big to convert
```

**Comment by jorisvandenbossche** [comment] 2016-04-29 19:14
Ah, duplicate of #11758. Please comment further there

**Closed** 2016-04-29 19:15 UTC
Labels: Bug, Timeseries
