### ISSUE TITLE
BUG: DatetimeIndex indexing fails at nanosecond precision if timezone is used

### ISSUE THREAD

**Issue by jzwinck** [pydata/pandas#13908] opened 2016-08-04 17:46 UTC
`DatetimeIndex` fails to find its own values if a timezone is used:

    index = pd.DatetimeIndex(['2016-06-28 08:30:00.123456789'], dtype='datetime64[ns, America/Chicago]')
    df = pd.DataFrame({'a':[10]}, index=index)
    df.loc[df.index[0]]

It fails with:

    *** KeyError: 'the label [2016-06-28 08:30:00.123456789-05:00] is not in the [index]'

This is impossible.

It works if you use only microseconds rather than nanoseconds, and it works if you don't set a timezone.

Pandas 0.18.1.

**Comment by jreback** [comment] 2016-08-04 20:30
this is a dupe of #11679

**Closed by jreback** 2016-08-04 20:30 UTC

**Comment by jreback** [comment] 2016-08-04 21:42
I am pretty sure
these are red herrings
the issue is caused by a problem in the indexer 
the effect is the same

in any event if you want to do a PR then u can confirm it

df.index[0] in df.index is what's failing

**Comment by jreback** [comment] 2017-06-28 09:31
This is fixed on master. If anyone wants to do a PR for the tests would be great. (originally linked to #11679, so that might be closable as well.)
