### ISSUE TITLE
Add some ExcelWriter Parameters

### ISSUE THREAD

**Issue by PanchoVarallo** [pydata/pandas#12978] opened 2016-04-25 08:17 UTC
The `ExcelWriter` class in line 550 of [pandas/pandas/io/excel.py](https://github.com/pydata/pandas/blob/6c692aee6d411d67997c4fadd023a1d4b7f91c12/pandas/io/excel.py#L550) takes a `datetime_format` parameter to format a datetime column.

Wouldn't it be useful to include a `font_size` parameter as well? Otherwise I don't see how I can set the font size apart from the hard way through `xlsxwriter`. Correct me if I am wrong.

**Comment by jreback** [comment] 2016-04-25 12:52
duplicate of this issue: https://github.com/pydata/pandas/issues/1663

styles are already possible, but its unoptimized, and not-documented.

**Closed by jreback** 2016-04-25 12:52 UTC
