### ISSUE TITLE
Add row filtering operator

### ISSUE THREAD

**Issue by elyase** [pydata/pandas#5900] opened 2014-01-10 17:07 UTC
This would allow chaining operations like:
```python
pd.read_csv('imdb.txt')
  .sort(columns='year')
  .filter(lambda x: x['year']>1990)   # <---this is missing in Pandas
  .to_csv('filtered.csv')
```
For current alternatives see:

http://stackoverflow.com/questions/11869910/pandas-filter-rows-of-dataframe-with-operator-chaining

**Comment by naught101** [comment] 2015-09-16 03:09
Might it be possible with patsy to make a filter method that uses a formula string?

```{python}
pd.read_csv('imdb.txt')
  .sort(columns='year')
  .filter('year >1990')
  .to_csv('filtered.csv')
```

**Comment by shoyer** [comment] 2015-09-16 03:52
@naught101 Using strings to filter dataframes is already possible. The method is `query`, e.g.,
`pd.DataFrame({'x': [1, 2, 3, 4, 5]}).query('x > 3')`

**Comment by jreback** [comment] 2015-09-16 21:17
I suppose ``.query`` *could* take lambda to provide this in-line type of chaining

**Comment by jreback** [comment] 2016-01-31 17:58
dupe of #11485 (which has more examples)

**Closed by jreback** 2016-01-31 17:58 UTC
Labels: API Design, Difficulty Intermediate, Effort Medium, Ideas, Indexing, Prio-high
