### ISSUE TITLE
Respect numpy fixed length strings

### ISSUE THREAD

**Issue by MaxNoe** [pydata/pandas#10351] opened 2015-06-14 11:59 UTC
pandas converts all strings to 'O' columns.

For consistency and writing to files it would be good if pandas respects numpy fixed length strings.

```
import numpy as np
import pandas as pd

df = pd.DataFrame({'date': np.array(['2015-10-10', '2015-01-01'], dtype='S10')})
print(df.date.dtype)
```
Results in `dtype('O')` and not `dtype('S10')`

**Comment by jreback** [comment] 2015-06-14 12:22
this would add quite a bit of complexity, so what exactly would be the gain here? 
as a side note, you are representing a datetime, which should almost certainly be coerced to a ``datetime64[ns]`` for any usage.

**Comment by MaxNoe** [comment] 2015-06-14 13:22
The date was just an example.

The gain would be that numpy operations on the underlying string array would be possible and
that one has not to care for a 'min_itemsize' in to_hdf or root_pandas 'to_root'

**Comment by jreback** [comment] 2015-06-14 13:31
you don't need to specify ``min_itemsize`` except if you need to anticipate a bigger string in another chunk, it will be computed automatically otherwise.

However, you have much greater complexity in the entire code base.

**Comment by bashtage** [comment] 2015-06-16 13:35
This seems nearly impossible.  What should happen in the following case?

```
df = pd.DataFrame({'date': np.array(['2015-10-10', '2015-01-01'], dtype='S10')})

df.iloc[0,0] = 'Some other string that is large'
```

The only manner I could imagine something like this being implemented would be to add a fixed-width-string-column type, like Categorical.  This column would have to be aware of the fixed size and do padding for strings that are too small (or raise) and raise for strings that are too large.  Seems like a lot effort to avoid a small number of function calls when writing data.

**Comment by jreback** [comment] 2015-06-17 10:47
yeh, I think I went thru this exercise before. The problem is that assignment might have to astype the entire array, which is completely inefficient. The ``S`` type would be nice if could mark a column as immutable (e.g. so for an ``Index`` type this could actually make sense). However, in almost all cases just use ``Categoricals`` and the efficient problem is solved anyhow.

closing, but if you want to discuss more, happy to.

**Comment by jreback** [comment] 2015-06-17 10:47
this is a dupe of #5261 as well.

**Closed by jreback** 2015-06-17 10:47 UTC
Labels: API Design, Dtypes, Needs Discussion

**Comment by stuz5000** [comment] 2018-07-03 17:43
Since pandas supports customs types now:
https://pandas.pydata.org/pandas-docs/version/0.23.1/whatsnew.html#whatsnew-023-enhancements-extension
can the same mechanism be used to support fixed width strings?

**Comment by jreback** [comment] 2018-07-03 18:03
in theory

but would require a community pull request to make this happen
