### ISSUE TITLE
Pandas read_sas error: 'ascii' codec can't decode byte 0xd8 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by randomgambit** [pydata/pandas#12809] opened 2016-04-05 23:54 UTC
Hello everybody,

I am using **Pandas 0.18** to open a `sas7bdat` dataset 

I simply use:

    df=pd.read_sas('P:/myfile.sas7bdat')

and I get the following error

        buf[0:text_block_size].rstrip(b"\x00 ").decode())
    
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 0: ordinal not in range(128)

If I use

    import sys
    reload(sys)
    sys.setdefaultencoding("utf-8")

I get

    UnicodeDecodeError: 'utf8' codec can't decode byte 0xd8 in position 0: invalid continuation byte

Other `sas7bdat` files in my folder are handled just fine by Pandas. 

When I open the file in SAS I see that the column names are very long and span several lines, but otherwise the files look just fine.

There are not so many possible options in `read_sas`... what should I do? Is this a bug in `read_sas`? 

Many thanks!

**Comment by TomAugspurger** [comment] 2016-04-06 00:06
Are you able to share that file, or a similar file with non-senstitive data that raises the same error?

**Comment by randomgambit** [comment] 2016-04-06 00:08
well this is the problem.. I cant. but I can do my best to run tests on my side, or do stuff in sas, or whatever you need to sort out the problem

**Comment by TomAugspurger** [comment] 2016-04-06 00:12
You said the lines were long and span several lines. Can you make a dummy file with long names (just random strings like `AAAAA....` might work) and a bit of fake data? (I don't have a copy of SAS). 

This might be a dupe of https://github.com/pydata/pandas/issues/12659 Can you try reading the file [linked there](https://github.com/pydata/pandas/blob/8857008178eb90b59ca67874507ef860b3faf88f/pandas/io/tests/sas/data/test17.sas7bdat) and see if the same error is raised?

**Comment by randomgambit** [comment] 2016-04-06 00:17
when I try to read that file, I get `TypeError: read() takes at most 1 argument (2 given)`

**Comment by TomAugspurger** [comment] 2016-04-06 00:19
Just making sure, did you click on the `raw` link to download?

https://github.com/pydata/pandas/raw/8857008178eb90b59ca67874507ef860b3faf88f/pandas/io/tests/sas/data/test17.sas7bdat

**Comment by randomgambit** [comment] 2016-04-06 00:22
yes, I dowloaded the file test17.sas7bdat. This is not the error expected?

**Comment by randomgambit** [comment] 2016-04-06 00:24
I checked the details of the file in SAS. Apparently it is encoded in latin 1 western.
So I tried read_sas('myfile', encoding=''latin_1") but I get the same error

**Comment by TomAugspurger** [comment] 2016-04-06 00:32
Sorry, I was mistaken about the error message. Looks like this is a different issue.

**Comment by randomgambit** [comment] 2016-04-06 00:34
something strange is that even if I specify some encoding, I still get some error relative to the ascii codec. Can that be a cause of the error?

**Comment by randomgambit** [comment] 2016-04-06 00:37
the encoding of my sas file is more precisely latin1 western ISO. Created in linux.

**Comment by TomAugspurger** [comment] 2016-04-06 00:48
Can you drop into the debugger after it raises the error? `%debug` if your in IPython. Then you can see what's going on.

The docstring says `encoding` is just for decoding string columns (the actual values), so perhaps it isn't being applied to decoding the column names.

**Comment by randomgambit** [comment] 2016-04-06 00:49
aha! ok lemme try the debugger

**Comment by randomgambit** [comment] 2016-04-06 01:32
```

> c:\users\me\appdata\local\continuum\anaconda2\lib\site-packages\pandas\io\sas\sas7bdat.py(529)_process_columntext_subheader()
    527         buf = self._read_bytes(offset, text_block_size)
    528         self.column_names_strings.append(
--> 529             buf[0:text_block_size].rstrip(b"\x00 ").decode())
    530 
    531         if len(self.column_names_strings) == 1:

```

**Comment by randomgambit** [comment] 2016-04-06 01:33
this is what I get. then the debugger seems to wait for instructions

**Comment by TomAugspurger** [comment] 2016-04-06 01:34
Ahh, that looks promising though. Does `buf[0:text_block_size].rstrip(b"\x00 ").decode('latin1')` work there?

**Comment by randomgambit** [comment] 2016-04-06 01:35
what do you mean? what should I do?

**Comment by randomgambit** [comment] 2016-04-06 12:20
OK Tom, I found a fix.

Just use check the encoding of your sas file (right click, properties, details) and set the encoding.

import sys
reload(sys)
sys.setdefaultencoding("latin-1")

the question I have is thus: why specifying the encoding in the read_sas function does nothing?

**Comment by TomAugspurger** [comment] 2016-04-06 12:26
I believe the `encoding` parameter is just used to decode text data in the actual DataFrame itself, and not the metadata like column headers. Does that sound correct @kshedden ?

**Comment by kshedden** [comment] 2016-04-06 12:43
According to the docs below, depending on the setting of the VALIDVARNAME
option, variable names may be either restricted to ASCII, or may be
arbitrary bytes to be decoded somehow:

http://support.sas.com/documentation/cdl/en/lrcon/68089/HTML/default/viewer.htm#p18cdcs4v5wd2dn1q0x296d3qek6.htm

I'm not sure if this VALIDVARNAME (which I have never heard of before) is
in the file somewhere, or is an option that you specify within the
session.  In any case, it appears that the column names may need to be
decoded.

Also relevant:

http://support.sas.com/documentation/cdl/en/nlsref/61893/HTML/default/viewer.htm#a002601944.htm

**Comment by randomgambit** [comment] 2016-04-06 13:02
yes, makes sense although I dont have any control over the creation of these sas files.

**Comment by kshedden** [comment] 2016-04-06 13:04
I'm working on a PR https://github.com/pydata/pandas/pull/12656 and will
try to work this into it.

I haven't had much time lately but will try to get to this next week.

Kerby

**Comment by kshedden** [comment] 2016-04-11 12:53
@randomgambit, can you try this branch against your SAS file:

https://github.com/kshedden/pandas/tree/sas7bdat_perf

I hope it fixes your problem.

**Closed** 2016-04-22 15:09 UTC
Labels: IO SAS, Unicode
