### ISSUE TITLE
GroupBy.apply calling function twice

### ISSUE THREAD

**Issue by cancan101** [pydata/pandas#10519] opened 2015-07-06 19:44 UTC
```python
def foo(x):
    print "hello"
_ = pd.DataFrame({'a':[1]}).groupby(["a"]).apply(foo)
```
```
hello
hello
```

**Comment by jreback** [comment] 2015-07-06 20:19
dupe of #2936 and its mentioned [here](http://pandas.pydata.org/pandas-docs/stable/groupby.html#flexible-apply) in the docs

**Closed by jreback** 2015-07-06 20:19 UTC

**Comment by cancan101** [comment] 2015-07-06 20:32
@jreback I am confused in reading those docs: what is the single run version of `apply` that can be used when I want to return a new dataframe for each grouping that is that concatenated to form one resulting dataframe?

e.g what is the simples way to apply this:
```
def foo(x):
    print 'xxx'
    return x
```
and have it called once per group and end up with the same dataset that went in coming out?

**Comment by jreback** [comment] 2015-07-06 20:36
``df.groupby(...).apply(foo)``

not sure why it matters if its called twice. This is only to determine there is mutation or not.

**Comment by cancan101** [comment] 2015-07-06 20:37
`foo` is a very expensive operation that I would prefer is run just once.

**Comment by jreback** [comment] 2015-07-06 20:38
then loop your self

```pd.concat([ (g, foo(grp)) for g, grp in df.groupby(....) ])``

**Comment by cancan101** [comment] 2015-07-06 20:41
Okay.
Should be:
```python
pd.concat([ foo(grp) for _, grp in df.groupby(...) ])
```
