### ISSUE TITLE
Sum of all NaNs comes out zero if bottleneck is installed

### ISSUE THREAD

**Issue by dieterv77** [pydata/pandas#13391] opened 2016-06-07 19:41 UTC
x = pandas.DataFrame(np.nan, index=['a', 'b'], columns=['c', 'd'])
print x.sum()

I expected to see all NaN's in the resulting Series.  However, if i have bottleneck installed i get a Series of all zeros instead of all NaNs.

This is with pandas 0.18.1.

Thanks for any comments or suggestions

**Comment by jreback** [comment] 2016-06-07 19:43
dupe of #9422 see long discussion there.

**Closed by jreback** 2016-06-07 19:43 UTC
