### ISSUE TITLE
API: DataFrame.eval, inplace option

### ISSUE THREAD

**Issue by shoyer** [pydata/pandas#9297] opened 2015-01-19 10:52 UTC
Building off of #9229, it's generally much better to create new dataframes rather than to modify existing ones. It's both more chainable and less prone to the bugs/errors associated with mutable state.

So it seems to me that a saner API design would be to make assignment operations with eval/query return a new frame rather than modify the existing one, i.e., `df.eval('x = y ** 2')` should be equivalent to `df.assign(x = lambda df: df.y ** 2)` (as currently defined in #9239).

In my experience, something like `df.query('x = 0')` is more likely intended to be equivalent to `df.query('x == 0')` rather than `df['x'] = 0`, which has the unfortunate effect of also modifying the original data. In fact, I have made this exact mistake before -- and apparently others have as well (see #8664).

Thoughts? The `query`/`eval` syntax is marked as experimental, so I think we have the freedom to change this.

CC @TomAugspurger @cpcloud @jreback

**Comment by jreback** [comment] 2015-01-19 11:26
pretty sure that this is converted to == or raises I don't recall which
query never should assign - iirc their is a another issue about this where it is reported - so this is a dupe issue

**Comment by jreback** [comment] 2015-01-19 12:17
dupe of #8664 (this is a bug an not an API issue).

**Comment by cpcloud** [comment] 2015-01-19 12:26
I think this is about eval mostly and that it should use the new assign, not the issue that assigning in query is a bug. Reopening.

**Comment by cpcloud** [comment] 2015-01-19 12:28
@jreback I know you're on an issue closing spree, feel free to "reclose". 😊

**Comment by jreback** [comment] 2015-01-19 12:30
oh ok. Yeh the query using ``=`` is a bug (and covered by #8864). It think ``eval`` is fine. 

So @shoyer maybe clarify what this issue is addressing.

**Comment by cpcloud** [comment] 2015-01-19 12:34
I think he's saying that instead of updating the frame and returning None, we should return a new frame with that column assigned to it. This would be a breaking api change, so I think an inplace flag would be nice to allow people minimal breakage. We could default to True for a few releases and then change to False

**Comment by jreback** [comment] 2015-01-19 12:49
ok, I can buy that for a $1

**Comment by shoyer** [comment] 2015-01-20 02:56
@cpcloud, thanks for your help clarifying. This is indeed my idea here. (Using query instead of eval in the example did not help :).)

**Comment by jreback** [comment] 2016-01-04 02:17
closed by #11149

**Closed by jreback** 2016-01-04 02:17 UTC
Labels: API Design
