### ISSUE TITLE
read_csv : string type not used for multiindex column

### ISSUE THREAD

**Issue by julienvienne** [pydata/pandas#9849] opened 2015-04-10 15:49 UTC
Hello,
I have a CSV like this :
```csv
POSTE;DATE;RR;TN;TX;SIGMA
06088001;20150316;8,1;7,4;14,1;11
06088001;20150317;0,6;9,8;15,6;0
```
First column designate a 8 character code which should be handled as a string. 
Second column is a datetime. The two columns are designated as index column with index_col argument :
```python
>>>df = read_csv(fileame, sep=";",
              header=0, 
              parse_dates=[1],
              decimal=",",  
              index_col=[0,1],
              dtype={"POSTE":str})
>>>df 
                       RR    TN    TX  SIGMA
POSTE    DATE                               
6088001  2015-03-16   8.1   7.4  14.1     11
         2015-03-17   0.6   9.8  15.6      0
```

As you can see, there is a missing "0" for POSTE column because it has been casted to integer, despite of `dtype={"POSTE":str}` argument. I also tried with `dtype={"POSTE":object}` instruction as indicated on forums it still gives the same result.

Apparently this only occurs only if column is used in an index column.
Column is not converted if I only use DATE for the index :
```python
>>> df = read_csv(fileame, sep=";",
              header=0, 
              parse_dates=[1],
              decimal=",",  
              index_col=[1],
              dtype={"POSTE":str})

>>> df 
            POSTE       RR    TN    TX  SIGMA
DATE                                         
2015-03-16  06088001   8.1   7.4  14.1     11
2015-03-17  06088001   0.6   9.8  15.6      0
```
I'm using Pandas v 0.14.1 so it may have been fixed recently.
Do you confirm this is not the correct behaviour ?

Regards

**Comment by jreback** [comment] 2015-04-11 15:20
this is a dupe of #9435 thanks for the report

**Closed by jreback** 2015-04-11 15:20 UTC
