### ISSUE TITLE
The documentation around frequency strings is unclear

### ISSUE THREAD

**Issue by mineo** [pydata/pandas#13160] opened 2016-05-12 19:05 UTC
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.rolling.html?highlight=rolling#pandas.DataFrame.rolling and various other places in the documentation talk about something called "frequency strings", however, there doesn't seem to be any explanation of what this term means anywhere. http://pandas.pydata.org/pandas-docs/stable/timeseries.html#dateoffset-objects mentions the term again without explaining it. From the few examples I found, I now think http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases (note that this is after the dateoffset objects in the documentation) is the complete list of frequency strings, but for some reason they're called "offset aliases" here. Are those the frequency strings? If not, where are they defined?

**Comment by sinhrks** [comment] 2016-05-12 23:32
I think another confusion is caused by legacy aliases.  We've formally deprecated legacy offsets in 0.17 (#10951), thus 0.19 may be good timing to re-organize the doc (including your point).

**Comment by ckrapu** [comment] 2016-05-13 19:06
I'd like to take this for my first PR. Could it be assigned to me?

**Comment by jreback** [comment] 2016-05-13 19:07
@ckrapu go ahead an submit a PR when you are ready.

**Comment by sahildua2305** [comment] 2016-07-12 21:20
@ckrapu are you still working on this? If not, I'd like to work on this. Please let me know.

**Comment by ckrapu** [comment] 2016-07-12 21:24
Nope, all yours. I got stuck trying to build the docs and sort out what
actually needed to be edited. If you do work on it, I'd really like to see
what you end up doing, as a sort of tutorial.

**Comment by sahildua2305** [comment] 2016-07-12 21:27
Awesome!

@jreback can you please suggest some ideas about including the point mentioned by @mineo? One thing can be including the link to [this](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases) explanation wherever `frequency string` is mentioned/used. Other approach I can think of is to bring the same explanation part in the beginning.

Am I thinking in the right direction?

**Comment by jreback** [comment] 2016-07-12 21:46
sure u can include the link

**Comment by sahildua2305** [comment] 2016-07-12 22:39
@jreback I am not sure from where I can edit [this](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.rolling.html?highlight=rolling#pandas.DataFrame.rolling) page. I think that it's coming up from the Class documentation in [`window.py`](https://github.com/pydata/pandas/blob/master/pandas/core/window.py#L263). Should I add additional note for the `frequency strings` here?

**Comment by jreback** [comment] 2016-07-12 22:40
that page is the actual doc-string defined in window.py

docs themselves r in pandas/doc/source

**Comment by sahildua2305** [comment] 2016-07-12 22:42
Thanks! I'll submit the PR in a while.

**Comment by jorisvandenbossche** [comment] 2016-07-13 10:03
@ckrapu If you got stuck with building the docs, always welcome to specify what the problem was, so we can try to make contributing to the documentation as easy as possible

**Closed** 2016-07-21 14:31 UTC
Labels: Difficulty Novice, Docs, Effort Low, Frequency
