### ISSUE TITLE
FloatArrayFormatter._format_strings cannot handle float arrays containing NaNs

### ISSUE THREAD

**Issue by willfurnass** [pydata/pandas#9759] opened 2015-03-31 11:55 UTC
Get `FloatingPointError` ([stack trace](http://pastebin.com/m1fZH4ie)) if call `to_html` method of a DataFrame that contains some NaN values.  To reproduce:

````python
import pandas as pd
import numpy as np
pd.DataFrame(data=[np.nan, 3, 4]).to_html()
````

The problem seems to be that `FloatArrayFormatter._format_strings` assumes that the array it is trying to format as a string contains no `np.nan` values when checking to see if the array contains any very large or very small values.

Version info:
```
commit: None
python: 3.4.3.final.0
OS: Linux
machine: x86_64
pandas: 0.16.0
Cython: 0.22
numpy: 1.9.2
```

**Comment by willfurnass** [comment] 2015-03-31 13:42
Fix proposed in pull request https://github.com/pydata/pandas/pull/9761

**Comment by jreback** [comment] 2015-04-02 20:27
```
In [2]: pd.DataFrame(data=[np.nan, 3, 4]).to_html()
Out[2]: '<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>0</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>4</td>\n    </tr>\n  </tbody>\n</table>'
```

works ok for me on 3.4.

are you sure you didn't do any ``np.seterr`` ?

**Comment by willfurnass** [comment] 2015-04-03 09:20
Sorry, you're quite right.  It was `np.seterr(invalid='raise')` that was contributing  to `FloatArrayFormatter._format_strings` generating a `FloatingPointError`.  

Is there a policy with regards to how pandas should support different error handling configurations?  At present it seems that behaviour when `invalid='raise'` is slightly inconsistent in that your test case above fails as previously described yet `pd.DataFrame(data=[np.nan, 3, 4]),to_json()` does not generate any errors.

**Comment by jreback** [comment] 2015-04-03 11:10
prob is I don't think we can support different error configurations - if the exceptions raise then very little of the nan handling works, not to mention division by zero

**Comment by jreback** [comment] 2015-04-04 18:34
closing as this is not a bug

**Closed by jreback** 2015-04-04 18:34 UTC

**Comment by willfurnass** [comment] 2015-04-08 09:19
Is there any interest in supporting `numpy.seterr` and the `numpy.errstate` context manager (or equivalents) in pandas?  Could be useful to force exceptions to be raised in situations where you really don't want NaNs or don't want inf values from things being divided by zero.  If not, then perhaps a note should be added to the docs explaining that anything other than the default numpy error handling will cause problems with pandas.

**Comment by jreback** [comment] 2015-04-08 12:22
There is an option to treat infs as nulls if you want.
```
mode.use_inf_as_null : boolean
    True means treat None, NaN, INF, -INF as null (old way),
    False means None and NaN are null, but INF, -INF are not null
    (new way).
    [default: False] [currently: False]
```

but by definition pandas must have this set (in fact it IS set by pandas). Changing is at your own risk (and to be honest this is the first time I have seen someone have a problem with it), though I did once myself a long time ago. If you think a note somewhere in the docs would help, then ok.
