### ISSUE TITLE
inconisitent behaviour of hdf5 store.append for MultiIndex vs simple Index

### ISSUE THREAD

**Issue by DSLituiev** [pydata/pandas#11364] opened 2015-10-18 21:20 UTC
The following example works with MultiIndex, but fails with simple index, which is bad in terms of generalization / intuitive behaviour:
```
#Create example:
col_nums = [0]
df = pd.DataFrame({"V1":["a","b","c","d","e", "aaaah!!!"], 
                          "W":["c","d","c","d","c","c"],
                          "data":np.arange(6)})
df.set_index(["V1","W"], inplace = True)
df.to_csv("testtable.tab",sep = "\t")
```

```
# MulitIndex -> works:
sep = "\t"
indexcols =[0,1]
chunksize=5

xbed = "testtable.tab"
%rm 'tempstore.h5'
# create a store
with pd.HDFStore('tempstore.h5') as store:
    for nn, chunk in enumerate(pd.read_table(xbed, chunksize=chunksize, sep = sep, index_col= indexcols)):
        group = "x"
        print(chunk.index.names)
        store.append(group, chunk, format = "table", 
                     min_itemsize=dict(zip(chunk.index.names, [32]*len(chunk.index.names))))
        print("chunk #" , nn, file = sys.stderr)
```

```
# simple Index -> fails:
sep = "\t"
indexcols =[0]    # <==== this is the only difference
chunksize=5

xbed = "testtable.tab"
%rm 'tempstore.h5'
# create a store
with pd.HDFStore('tempstore.h5') as store:
    for nn, chunk in enumerate(pd.read_table(xbed, chunksize=chunksize, sep = sep, index_col= indexcols)):
        group = "x"
        print(chunk.index.names)
        store.append(group, chunk, format = "table", 
                     min_itemsize=dict(zip(chunk.index.names, [32]*len(chunk.index.names))))
        print("chunk #" , nn, file = sys.stderr)
```
` -> ...  ValueError: min_itemsize has the key [V1] which is not an axis or data_column`

**Comment by jreback** [comment] 2015-10-18 23:20
yeh, this is a dupe of: https://github.com/pydata/pandas/issues/10381

``min_itemsize = {'index' : 10}`` should be synonymous with ``min_itemsize = {index.name : 10}``

a pull-request to fix would be welcome (and should be straightforward)

**Closed by jreback** 2015-10-18 23:20 UTC

**Comment by DSLituiev** [comment] 2015-10-19 02:58
can you give a hint where are `Table.non_index_axes` set?

**Comment by jreback** [comment] 2015-10-19 03:13
https://github.com/pydata/pandas/blob/master/pandas/io/pytables.py#L3347

**Comment by DSLituiev** [comment] 2015-10-19 05:50
thank you!
where are test files located? shall I add a test for this issue?
