### ISSUE TITLE
Timezones for PeriodIndex

### ISSUE THREAD

**Issue by changhiskhan** [pydata/pandas#2106] opened 2012-10-23 15:53 UTC
from SO: http://stackoverflow.com/questions/13030402/pandas-plot-function-ignores-timezone-of-timeseries

**Comment by amelio-vazquez-reina** [comment] 2016-01-07 18:41
I am having the same problem here with the latest stable version of Pandas.

**Comment by jreback** [comment] 2016-01-07 18:44
these r not supported

**Comment by vgoklani** [comment] 2016-05-28 02:41
same issue, what's not supported?

**Comment by jreback** [comment] 2016-05-28 17:04
``Periods`` don't support timezone. Plotting needs to convert to a local tz before creating the periods.

**Comment by emunsing** [comment] 2016-10-12 18:39
As a workaround, you can remove the timezone info from the DateTimeIndex of the data which you're wishing to plot using `.tz_localize(None)` which will preserve the values but strip the timezone information.  Matplotlib/pyplot will see these naive datetime values and assume that they are UTC, and will happily plot them with working x-axis ticks.

**Comment by jreback** [comment] 2016-10-12 18:44
going to close this issue. This add needless complication because Periods can actually fall in more than 1 tz (e.g. on a DST change), when tz's are quite well supported on DTIs / Timestamps and the conversions are pretty straightforward.

**Closed by jreback** 2016-10-12 18:44 UTC
Labels: Indexing, Period, Timezones, Visualization

**Comment by stroobandt** [comment] 2017-10-03 21:31
This [StackExchange response](https://stackoverflow.com/a/13034577/2192488) leads to this issue.
Any kind of solution to this issue still seems to be appreciated.

**Comment by AvverbioPronome** [comment] 2020-04-15 11:53
@stroobandt this is the solution I ended up using, I chose a timezone for the plot, and go with this:

```python
import matplotlib.pytplot as plt, pandas as pd
df = pd.Dataframe(...)
fig, ax = plt.subplots()
df.plot(ax=ax)
import matplotlib.dates as mdates                                                                                   
from pytz import timezone                                                                                           
ax.xaxis.set_major_formatter(mdates.DateFormatter('%d/%m %H:%M', timezone('Europe/Amsterdam'))) 
fig.show()
```

**Comment by joooeey** [comment] 2022-08-05 11:36
I just tried to reproduce the issue described on StackOverflow and couldn't. Pandas plots the graph in whatever timezone the data is passed. That's exactly what a typical user would expect. The timezone is not mentioned anywhere on the plot.

Code from [StackOverflow](https://stackoverflow.com/questions/13030402/pandas-plot-function-ignores-timezone-of-timeseries/13034577#13034577):
```
import numpy as np
import matplotlib.pyplot as plt
from pandas import DataFrame, date_range

rng = date_range('1/1/2011', periods=200, freq='S', tz="UTC")
data = DataFrame(np.random.randn(len(rng), 3), index=rng, columns=['A', 'B', 'C'])
data_cet = data.tz_convert("CET")

# plot with data in UTC timezone
fig, ax = plt.subplots()
data[["A", "B"]].plot(ax=ax, grid=True)
plt.show()

# plot with data in CET timezone, but the x-axis remains the same as above
fig, ax = plt.subplots()
data_cet[["A", "B"]].plot(ax=ax, grid=True)
plt.show()
```
UTC figure:

![Figure_1](https://user-images.githubusercontent.com/28426758/183069186-5e35756f-27d2-40a3-83d6-1b081392d20e.png)

CET figure:

![Figure_2](https://user-images.githubusercontent.com/28426758/183069216-f94396f8-998c-4849-b2ed-dfe64427593c.png)

This is on Pandas 1.2.4.
