### ISSUE TITLE
tuples as data not filter-able for equality?

### ISSUE THREAD

**Issue by michaelaye** [pydata/pandas#11137] opened 2015-09-17 19:48 UTC
Using 
'0.17.0rc1+31.g9be2180'
and  a column of tuples like so:
```python
df.BINNING_SET.head()

TIME_OF_INT
2014-10-18 07:36:19.926570     (0, 1, 319, 11)
2014-10-18 07:36:19.926570     (0, 1, 441, 11)
2014-10-18 07:36:59.675040    (52, 4, 89, 115)
2014-10-18 07:36:59.675040    (2, 34, 96, 115)
2014-10-18 07:55:27.922290    (52, 4, 89, 115)
Name: BINNING_SET, dtype: object
```
I can't seem to filter on any tuple like so:
```python
df.BINNING_SET==df.BINNING_SET.iloc[0]

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-41-435fa8bdd1a7> in <module>()
----> 1 df.BINNING_SET==df.BINNING_SET.iloc[0]

/Users/klay6683/miniconda3/lib/python3.4/site-packages/pandas-0.17.0rc1+31.g9be2180-py3.4-macosx-10.5-x86_64.egg/pandas/core/ops.py in wrapper(self, other, axis)
    724                 other = np.asarray(other)
    725 
--> 726             res = na_op(values, other)
    727             if isscalar(res):
    728                 raise TypeError('Could not compare %s type with Series'

/Users/klay6683/miniconda3/lib/python3.4/site-packages/pandas-0.17.0rc1+31.g9be2180-py3.4-macosx-10.5-x86_64.egg/pandas/core/ops.py in na_op(x, y)
    642             if isinstance(y, (np.ndarray, pd.Series)):
    643                 if not is_object_dtype(y.dtype):
--> 644                     result = lib.vec_compare(x, y.astype(np.object_), op)
    645                 else:
    646                     result = lib.vec_compare(x, y, op)

pandas/lib.pyx in pandas.lib.vec_compare (pandas/lib.c:14361)()

ValueError: Arrays were different lengths: 41994 vs 4
```

**Comment by maximilianr** [comment] 2015-09-17 20:01
Looks like it's trying to compare your whole series to the tuple, because the tuple is a sequence.

You can (practically) only support either a comparison of a series to a sequence, or a comparison of each point of a series to a sequence; not both.

Solution is fairly consistent to both https://github.com/pydata/pandas/issues/10900 and https://github.com/pydata/pandas/issues/10399 - is there a reason you can't use a DataFrame here?

**Comment by michaelaye** [comment] 2015-09-17 20:31
I'm a bit confused, because before it was said that this problem would only appear when using df.apply. I think this basically just boils down to pandas not supporting tuples as object elements, as the operation I'm doing above is a fully supported on in general, isn't it? I'm unclear on what you mean by "using a DataFrame"?

**Comment by maximilianr** [comment] 2015-09-17 21:04
@michaelaye Yes exactly - you may be constantly struggling if you try and use sequences as object elements. Others who are closer to the project should weigh in here though.

Re the DataFrame - I didn't see that this is a column in a DataFrame already. My suggestion isn't very helpful, then.

This does seem like a reversion, FWIW:
```python
series=pd.Series(tuple(pd.np.random.rand(3)) for _ in range(20))
series==series.iloc[0]
# 0      True
# 1     False
# ...
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Darwin
OS-release: 14.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.16.2
```

```python
In [2]: series=pd.Series(tuple(pd.np.random.rand(3)) for _ in range(20))

In [3]: series==series.iloc[0]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-83f74919dc93> in <module>()
----> 1 series==series.iloc[0]

/Users/maximilian/Dropbox/workspace/pandas/pandas/core/ops.py in wrapper(self, other, axis)
    724                 other = np.asarray(other)
    725 
--> 726             res = na_op(values, other)
    727             if isscalar(res):
    728                 raise TypeError('Could not compare %s type with Series'

/Users/maximilian/Dropbox/workspace/pandas/pandas/core/ops.py in na_op(x, y)
    642             if isinstance(y, (np.ndarray, pd.Series)):
    643                 if not is_object_dtype(y.dtype):
--> 644                     result = lib.vec_compare(x, y.astype(np.object_), op)
    645                 else:
    646                     result = lib.vec_compare(x, y, op)

/Users/maximilian/Dropbox/workspace/pandas/pandas/lib.pyx in pandas.lib.vec_compare (pandas/lib.c:13811)()
    799 
    800     if n != len(right):
--> 801         raise ValueError('Arrays were different lengths: %d vs %d'
    802                          % (n, len(right)))
    803 

ValueError: Arrays were different lengths: 20 vs 3

In [5]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: d28fd702c87f4c2629c53d763551feb5395ff8b5
python: 3.4.3.final.0
python-bits: 64
OS: Darwin
OS-release: 14.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.0rc1+60.gd28fd70
```

**Comment by michaelaye** [comment] 2015-09-17 21:08
That would explain why @jreback before only sounded like it's only an issue for df.appy. I'm sure if using tuples is a general problem, he would have warned me. (Or he did, and I wasn't listening. ;) )

**Comment by chris-b1** [comment] 2015-09-17 21:20
I know this has been suggested before...but why not store the tuple as `DataFrame` columns?  It's more idiomatic, and will be faster / more memory efficient.  If all you ever want to do is access the columns as group, just define something like a `fields` accessor as I did below.

    In [144]: df
    Out[144]: 
                                    BINNING_SET
    2014-10-18 07:36:19.926570   (0, 1, 319, 11)
    2014-10-18 07:36:19.926570   (0, 1, 441, 11)
    2014-10-18 07:36:59.675040  (52, 4, 89, 115)
    2014-10-18 07:36:59.675040  (2, 34, 96, 115)
    2014-10-18 07:55:27.922290  (52, 4, 89, 115)

    In [145]: fields = ['f1', 'f2', 'f3', 'f4']  #names for tuple components...

    In [146]: df = df.BINNING_SET.apply(lambda x: pd.Series(x, index=fields))

    In [147]: df
    Out[147]: 
                                f1  f2   f3   f4
    2014-10-18 07:36:19.926570   0   1  319   11
    2014-10-18 07:36:19.926570   0   1  441   11
    2014-10-18 07:36:59.675040  52   4   89  115
    2014-10-18 07:36:59.675040   2  34   96  115
    2014-10-18 07:55:27.922290  52   4   89  115

    In [152]: df[(df[fields] == df[fields].iloc[0]).all(1)]
    Out[152]: 
                                f1  f2   f3  f4
    2014-10-18 07:36:19.926570   0   1  319  11

**Comment by michaelaye** [comment] 2015-09-17 23:17
Thanks, that looks like a not too bad alternative, although the syntax is on the verge of becoming hard to read with this additional `.all(1)`. 
Yes, the main reason why working in tuples was a way to filter for a set of these values at once.

**Comment by jreback** [comment] 2015-09-17 23:21
@michaelaye you simply need to use a column MultiIndex (e.g. say you have several sets of these tuples).

```
In [8]: df = DataFrame(np.random.randn(6,4),index=pd.date_range('20130101',periods=6,freq='2s'),columns=pd.MultiIndex.from_product([list('AB'),range(2)]))

In [9]: df
Out[9]: 
                            A                   B          
                            0         1         0         1
2013-01-01 00:00:00 -0.296009 -0.374544  1.168945 -1.406648
2013-01-01 00:00:02 -0.532468 -0.540057 -0.022324 -0.395088
2013-01-01 00:00:04 -0.742925 -0.051457 -1.107048  0.549880
2013-01-01 00:00:06  1.070147 -0.205438  0.563086 -0.540265
2013-01-01 00:00:08 -0.128169 -0.219555  0.208610  0.438773
2013-01-01 00:00:10  1.287697 -0.496478 -0.266373  0.810742

In [11]: df[['A']]
Out[11]: 
                            A          
                            0         1
2013-01-01 00:00:00 -0.296009 -0.374544
2013-01-01 00:00:02 -0.532468 -0.540057
2013-01-01 00:00:04 -0.742925 -0.051457
2013-01-01 00:00:06  1.070147 -0.205438
2013-01-01 00:00:08 -0.128169 -0.219555
2013-01-01 00:00:10  1.287697 -0.496478
```

**Comment by michaelaye** [comment] 2015-09-17 23:37
Hm, my binning sets are just 4 out of a 20-30 column dataframe, so, IIUC, to use the MultiIndex way for different combinations of binning set numbers, I would have to repeat all the other columns, each time, correct? IIUC, you mean something like this:

```python
Out[147]: 
                            f1  f2   f3   f4  v1  v2
2014-10-18 07:36:19.926570   0   1  319   11   1   3
2014-10-18 07:36:19.926570   0   1  441   11   2   4
2014-10-18 07:36:59.675040  52   4   89  115   3   7
2014-10-18 07:36:59.675040   2  34   96  115   5   9
2014-10-18 07:55:27.922290  52   4   89  115   4   1
```
would become

```python
Out[147]: 
                           (0,1,319,11)        (0,1,441,11)
                                     v1   v2             v1   v2
2014-10-18 07:36:19.926570            1   3               2    4
```

**Comment by jreback** [comment] 2015-09-17 23:41
no that is very odd to use a *tuple* as an indexer in a ``MultiIndex``. These should simply be strings.

```
In [13]: df = DataFrame(np.random.randn(6,5),index=pd.date_range('20130101',periods=6,freq='2s'),columns=pd.MultiIndex.from_tuples([('f',1),('f',2),('f',3),('v',1),('v',2)]))

In [14]: df
Out[14]: 
                            f                             v          
                            1         2         3         1         2
2013-01-01 00:00:00 -1.165661 -1.181265 -0.126375 -0.834884 -0.357954
2013-01-01 00:00:02  1.087771 -0.529879  0.822059 -0.213104 -0.363985
2013-01-01 00:00:04 -0.246989 -1.611963  0.619888 -0.007096  0.115296
2013-01-01 00:00:06 -1.271250  0.011331 -0.698223 -0.471338 -0.391065
2013-01-01 00:00:08  0.752136 -0.133435 -1.394301 -0.923060  0.301170
2013-01-01 00:00:10  0.053189  0.459304 -2.736818 -0.365441  0.616951

In [15]: df[['v']]
Out[15]: 
                            v          
                            1         2
2013-01-01 00:00:00 -0.834884 -0.357954
2013-01-01 00:00:02 -0.213104 -0.363985
2013-01-01 00:00:04 -0.007096  0.115296
2013-01-01 00:00:06 -0.471338 -0.391065
2013-01-01 00:00:08 -0.923060  0.301170
2013-01-01 00:00:10 -0.365441  0.616951
```

**Comment by michaelaye** [comment] 2015-09-17 23:48
Well, I need to retain the values of the binning set, because they have mathematical meaning that I need to apply later on in the process. Of course I could store them somewhere in a dictionary, but that sounds like becoming more complicated than it needs to be.
The other advantage of having these 4 numbers as a tuple is that I am able to do `groupby` operations over it. Interestingly, pandas head does not have a problem doing that, while the equality check fails.

**Comment by jreback** [comment] 2015-09-17 23:51
ok, I guess I don't understand what your issue is. In order to see if their is an actual problem, I would need a self contained reproducible example. 

closing, but you can post here.

**Comment by michaelaye** [comment] 2015-09-17 23:51
The above mentioned regression is not an issue per se?

**Closed by jreback** 2015-09-17 23:51 UTC

**Comment by maximilianr** [comment] 2015-09-18 05:09
For reference, this was the commit that caused the change: https://github.com/pydata/pandas/commit/4fe7c68728da2174f7ccd290a43e358f16a1a6f9
