### ISSUE TITLE
Setting values on a DataFrame with tz aware DatetimeIndex fails

### ISSUE THREAD

**Issue by szs8** [pydata/pandas#12104] opened 2016-01-20 22:47 UTC
```python

tdf = pd.DataFrame({'a': np.arange(10), 'b': np.arange(10) + 5}, 
                   index=pd.date_range('20160119 09:00', freq='5T', 
                                       periods=10, tz='US/Eastern'))
new_values = tdf.sample(2)['b'] + 100
tdf.loc[new_values.index, 'b'] = new_values.values
```
This fails with ```KeyError: "['2016-01-19T14:00:00.000000000+0000' '2016-01-19T14:05:00.000000000+0000'] not in index```

This used to work. Not sure which version broke it.

**Comment by jreback** [comment] 2016-01-20 23:04
this is a dupe of #12050, already fixed in master and will be in 0.18.0

thanks for the report

**Closed by jreback** 2016-01-20 23:04 UTC
