### ISSUE TITLE
read_html: support "decimal" argument for parsing numbers, like read_csv

### ISSUE THREAD

**Issue by educhana** [pydata/pandas#12907] opened 2016-04-16 11:48 UTC
read_csv has support for declaring the decimal and thousands separator.

read_html is missing the 'decimal' parameter. it'd be useful and more consistent to accept it too.

Example:
```
pd.read_html(html, thousands='.', decimal=',')
```

**Comment by jreback** [comment] 2016-04-17 13:59
this is a dupe of #8200 but we'll close that issue. This should be straightforward and just need to pass this thru to the parser. Pull-requests are welcome.

**Comment by sldion** [comment] 2016-04-20 13:20
I don't think that `TextParser` supports passing the decimal keyword in python. The functionality probably needs to be added to PythonParser

**Closed** 2016-05-27 00:15 UTC
Labels: Difficulty Novice, Effort Low, Enhancement, IO HTML
