### ISSUE TITLE
multiple tests errors and failures while building 0.18.1+git25-ga7469cf on i386 (ok on amd64)

### ISSUE THREAD

**Issue by yarikoptic** [pydata/pandas#14288] opened 2016-09-23 12:12 UTC
#### Code Sample, a copy-pastable example if possible
```shell
% grep -2 '^\(FAIL\|ERROR\|[^ ]*Error:\)' pandas_0.18.1+git25-ga7469cf-1~nd90+1_i386.build

======================================================================
ERROR: test_groupby (pandas.tests.test_categorical.TestCategoricalAsBlock)
----------------------------------------------------------------------
Traceback (most recent call last):
--
  File "/build/pandas-0.18.1+git25-ga7469cf/debian/tmp/usr/lib/python2.7/dist-packages/pandas/core/groupby.py", line 4433, in _groupby_indices
    counts = np.bincount(codes[mask], minlength=values.categories.size)
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'

======================================================================
ERROR: test_get_group_empty_bins (pandas.tests.test_groupby.TestGroupBy)
----------------------------------------------------------------------
Traceback (most recent call last):
--
  File "/build/pandas-0.18.1+git25-ga7469cf/debian/tmp/usr/lib/python2.7/dist-packages/pandas/core/groupby.py", line 4433, in _groupby_indices
    counts = np.bincount(codes[mask], minlength=values.categories.size)
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'

======================================================================
FAIL: test_nat (pandas.tseries.tests.test_base.TestDatetimeIndexOps)
----------------------------------------------------------------------
Traceback (most recent call last):
--
  File "/build/pandas-0.18.1+git25-ga7469cf/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 1018, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: numpy array are different

Attribute "dtype" are different
--
======================================================================
FAIL: test_nat (pandas.tseries.tests.test_base.TestPeriodIndexOps)
----------------------------------------------------------------------
Traceback (most recent call last):
--
  File "/build/pandas-0.18.1+git25-ga7469cf/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 1018, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: numpy array are different

Attribute "dtype" are different
--
======================================================================
FAIL: test_nat (pandas.tseries.tests.test_base.TestTimedeltaIndexOps)
----------------------------------------------------------------------
Traceback (most recent call last):
--
  File "/build/pandas-0.18.1+git25-ga7469cf/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 1018, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: numpy array are different

Attribute "dtype" are different
--
Ran 10942 tests in 1071.084s

FAILED (SKIP=284, errors=2, failures=3)
True
WHAT THE
```
#### output of ``pd.show_versions()``

all the versions and more info is in the full build log: http://neuro.debian.net/_files/_buildlogs/pandas/0.18.1+git25-ga7469cf/pandas_0.18.1+git25-ga7469cf-1_amd64.build  but altogether versions are close/the same as in https://github.com/pydata/pandas/issues/14269#issue-178334362

**Comment by jreback** [comment] 2016-09-23 12:22
duplicate of #14183

**Comment by jreback** [comment] 2016-09-23 12:23
we do very little testing on 32-bit windows, so patches from the community welcome.

**Closed by jreback** 2016-09-23 12:22 UTC
