### ISSUE TITLE
Series.apply loses timezone information

### ISSUE THREAD

**Issue by compandu** [pydata/pandas#11800] opened 2015-12-09 09:05 UTC
apply seems to lose timezone awareness. Would expect the following to be invariant:

```python
In [9]: import pandas as pd

In [10]: pd.__version__
Out[10]: u'0.17.1'

In [11]: ser = pd.Series([pd.Timestamp('2015/01/01', tz='UTC'), pd.Timestamp('2015/01/02', tz='UTC')])

In [12]: ser
Out[12]: 
0   2015-01-01 00:00:00+00:00
1   2015-01-02 00:00:00+00:00
dtype: datetime64[ns, UTC]

In [13]: ser.apply(lambda x: x)
Out[13]: 
0   2015-01-01
1   2015-01-02
dtype: datetime64[ns]
```

**Comment by jreback** [comment] 2015-12-09 14:16
xref #11564 

cc @kawochen 

yeh, ``.apply`` return inference is being revamped as of above.

**Comment by jreback** [comment] 2015-12-12 14:05
yep this is a dupe of #11757

**Closed by jreback** 2015-12-12 14:05 UTC
Labels: Bug, Difficulty Intermediate, Effort Low, Timezones
