### ISSUE TITLE
Non consistent behavior with Dataframe.sum

### ISSUE THREAD

**Issue by Tux1** [pydata/pandas#11409] opened 2015-10-22 12:19 UTC
Hello,

I noticed a strange behavior involving important errors in my scripts.
```python
a = pd.DataFrame(np.nan, index=[1,2], columns=[3,4]).astype(np.float64)
b = pd.DataFrame(np.nan, index=[1,2], columns=[3,4]).astype(np.float32)
c = pd.DataFrame(np.nan, index=[1,2], columns=[3,4])
d = pd.DataFrame(index=[1,2], columns=[3,4])

print(a.sum())
3    0
4    0
dtype: float64
print(b.sum())
3   NaN
4   NaN
dtype: float64
print(c.sum())
3    0
4    0
dtype: float64
print(d.sum())
3   NaN
4   NaN
dtype: float64
```

According to your doc, the right result should be the second and fourth output. 
I guess it is due to Numpy changes 0.18. However I want to point out that numpy's choice is not good. A sum of NaN must not be zero. 

First argument is about logic : Nothing + Nothing is not something but Nothing + object could be something. Two things which are not number can not be a number by arithmetic operation

Second argument : it's easy to fill the result with zeros if you don't want NaN values. 
```python
a = pd.DataFrame(np.nan, index=[1,2], columns=[3,4]).sum()
a.fillna(0, inplace=0)
```
Whereas you are not able to fill the result with NaN instead of zeros into NaN rows (or columns whatever..) if they have been filled with zeros before (easily). I hope you see 
what I mean...

Thanks for your work ;)

**Comment by jreback** [comment] 2015-10-22 12:34
this is related to #9422 

pandas defers to bottleneck for these reductions. if you have bottlneck >= 1.0 then the results will be as above. if you have an older version that you would get all ``NaN`` results.

This is the numpy idea of the difference between ``nansum`` and ``sum``.

I happen to agree with you as you are effectively losing information, though @shoyer thinks we should keep in sync with numpy. 

you can control this via the ``skipna`` parameter.
```
In [17]: a.sum(skipna=False)
Out[17]: 
3   NaN
4   NaN
dtype: float64

In [18]: a.sum(skipna=True)
Out[18]: 
3    0
4    0
dtype: float64
```

**Comment by jreback** [comment] 2015-10-22 12:35
this is a dupe of #9422  in any event

**Closed by jreback** 2015-10-22 12:35 UTC
Labels: Numeric

**Comment by Tux1** [comment] 2015-10-22 14:43
The difference of behaviour between float32 and float64 is normal as well ? This is from bottleneck as well ?

**Comment by Tux1** [comment] 2015-10-22 14:45
The difference of behaviour between float32 and float64 is also due to bottleneck ?

**Comment by jreback** [comment] 2015-10-22 15:10
I think so you would have to trace this thru to be sure though
