### ISSUE TITLE
Series/DataFrame lookup values behave inconsistently

### ISSUE THREAD

**Issue by yueatwork** [pydata/pandas#11998] opened 2016-01-08 16:57 UTC
One feature about DataFrame that I found uncomfortable is the inconsistency of results:

    x = pd.DataFrame({'A': [1,2,3,4,5]}, index=['a','b','c','d','e'])
    x.loc[['a', 'f']]  # fine, value of 'f' is numpy.nan
    x.loc[['f']]  # throws 

When developing data applications, I spend lot of time fixing this issue.  I think we should make it more consistent. Either always returns (preferred) or always throws.

**Comment by jreback** [comment] 2016-01-08 18:26
duplicate of https://github.com/pydata/pandas/issues/10695

lots of discussion there.

**Closed by jreback** 2016-01-08 18:26 UTC

**Comment by jreback** [comment] 2016-01-08 18:27
this has nothing to do with ``Series/DataFrame``, they both work the same. rather whether a single missing label raises, while a list that includes at least one label will be like a ``.reindex``

**Comment by yueatwork** [comment] 2016-01-08 21:04
Thank you. Seems this isn't an easy fix. I will stick with the current framework until I figure out a better design.
