### ISSUE TITLE
pandas.DataFrame.to_html()  does not provide an option to remove all styling attributes

### ISSUE THREAD

**Issue by MikaS** [pydata/pandas#13887] opened 2016-08-03 16:04 UTC
DataFrame.to_html() renders by default a table element with a border='1' attribute. The text-align style attribute on the <thead> <tr> is also set to "right".
Even if it is easy to override by code or CSS, it should be good to have an option that removes or clear all styling attributes on the generated table. For example df.to_html(no_style=True)
Cheers,
Mikaël

**Comment by chris-b1** [comment] 2016-08-03 19:41
If you use the new [style API](http://pandas.pydata.org/pandas-docs/stable/style.html) the empty case (`df.style.render()`) does not have any style attributes.

**Comment by jreback** [comment] 2016-08-03 19:47
in any event, this is a dupe of #11563

**Closed by jreback** 2016-08-03 19:47 UTC
