### ISSUE TITLE
Invalid calculation of MINfloat16/MAXfloat16 in pandas/algos.pyx

### ISSUE THREAD

**Issue by vonosmas** [pydata/pandas#10046] opened 2015-05-02 01:02 UTC
The code generated by Cython from pandas/algos.pyx contains an undefined behavior (invalid cast of floating-point number to integer):
```
easy_install -U Cython
git clone git://github.com/pydata/pandas.git
python setup.py install
```

The generated code for the line from `pandas/algos.pyx`
```python
cdef np.float16_t MINfloat16 = np.NINF
```
in `pandas/algos.c` contains:
```c
typedef npy_float16 __pyx_t_5numpy_float16_t;
//... more code
__pyx_t_5numpy_float16_t __pyx_t_10;
//... more code
__pyx_t_10 = __pyx_PyFloat_AsFloat(__pyx_t_1);
```

The file `numpy-1.9.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/npy_common.h`
defines `npy_float16` as 16-bit *integer* type (I guess numpy implementation has a custom code that carefully represents these 16 bits as mantiss+exponent). Casting floating-point value `-inf` to a 16-bit integer type is an undefined behavior according to C standard.

I wasn't able to find any place in pandas code that uses `MINfloat16` (and `MAXfloat16`). Is it safe to just delete them?

**Comment by jreback** [comment] 2015-05-02 01:13
can u show an example with the error?

the float16 constants are prob hanging around - as it's not an explicitly supported type (though u can actually pass an array in) - it's just that all of the algos will cast

**Comment by vonosmas** [comment] 2015-05-02 01:45
Unfortunately, I see this error only if I compile generated `.c` files with `clang -fsanitize=float-cast-overflow` (http://clang.llvm.org/docs/UsersManual.html#controlling-code-generation). Looks like Cython directives are somewhat limited... Let me know if I should craft reproduction steps.

**Comment by jreback** [comment] 2015-06-18 15:22
dupe of #10382

**Closed by jreback** 2015-06-18 15:22 UTC
Labels: Build, Numeric
