### ISSUE TITLE
read_html leading zero problem

### ISSUE THREAD

**Issue by Matt2520** [pydata/pandas#11994] opened 2016-01-07 21:52 UTC
Hi, new to python and pandas, but am trying to work with information off the web that has serial numbers. Many of the numbers have leading zeros which that are important to carry over, but pandas interprets the values as integers and drops the zero. I was trying to change the dtype to str but read_html doesn't have a dtype argument, and it seems like infer_types = False is depricated (or at least I get an exception for unexpected keyword argument). What is the best way to get these zeros back?

**Comment by jreback** [comment] 2016-01-07 21:59
dupe of https://github.com/pydata/pandas/issues/10534

we are not passing thru the ``dtype`` argument to enable this.

you can certainly do this on post processing if you wanted. by doing an ``astype(object)``

**Closed by jreback** 2016-01-07 21:59 UTC
