### ISSUE TITLE
Segmentation fault happens when read_csv loads a big csv file

### ISSUE THREAD

**Issue by adri0** [pydata/pandas#11419] opened 2015-10-23 14:02 UTC
Today I decided to upgrade pandas from 0.16.2 to 0.17.0, and I started to get a segmentation fault when reading a big csv file with the `read_csv` method. If I simply type the following code below in the python terminal, loading an 160Mb csv file, my script crashes displaying a segmentation fault message. Although, if I use smaller files it works properly.

```python
>>> import pandas as pd
>>> df = pd.read_csv("big_csv.csv")
```

When downgrading back to 0.16.2, it starts to work again. If I use `engine='python'` argument, it also works. So, that's probably revealing some problem in the C engine.

I'm running everything on Ubuntu 14.04 x86_64

**Comment by jreback** [comment] 2015-10-23 14:04
@adri0 pls post something that someone can actually run. Either a link to the file, or much better a short reproducible example.

**Comment by toniatop** [comment] 2015-10-26 04:30
It seem similar to #11332 (same error on same platform).
Can you try:
```python
data = """ID
00013007854817840016671868
00013007854817840016749251
00013007854817840016754630
00013007854817840016781876
00013007854817840017028824
00013007854817840017963235
00013007854817840018860166"""
import pandas as pd
from StringIO import StringIO
result = pd.read_csv(StringIO(data))
```

**Comment by adri0** [comment] 2015-10-26 09:03
Right, @toniatop I tried your snippet and got a segfault with pandas 0.17.0. Then, tried it again using pandas 0.16.2, everything okay.

**Comment by jreback** [comment] 2015-10-26 11:13
closing as dupe of #11332

**Closed by jreback** 2015-10-26 11:13 UTC
Labels: CSV

**Comment by jreback** [comment] 2015-10-26 11:47
This should allow it to work

```
In [8]: pd.read_csv(StringIO(data),dtype={'ID' : object})       
Out[8]: 
                           ID
0  00013007854817840016671868
1  00013007854817840016749251
2  00013007854817840016754630
3  00013007854817840016781876
4  00013007854817840017028824
5  00013007854817840017963235
6  00013007854817840018860166
```
