### ISSUE TITLE
Pivot_table with categorical data gives ValueError

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#10028] opened 2015-04-30 08:49 UTC
This errors for me on master as well: http://stackoverflow.com/questions/29945342/pandas-error-with-pivot-table-and-categorical-data

```
  category1   category2  numeric
0      grey    complete        1
1      grey    complete        2
2       NaN  incomplete        3
3      blue    complete        4
```

```
In [13]: df = pd.read_clipboard()

# with plain strings it works

In [16]: pd.pivot_table(df, index = 'category1', columns = 'category2', values = 'numeric', aggfunc = 'count')
Out[16]:
category2  complete
category1
blue              1
grey              2

In [17]: df['category1'] = df['category1'].astype('category')

In [18]: df['category2'] = df['category2'].astype('category')

In [19]: pd.pivot_table(df, index = 'category1', columns = 'category2', values =
 'numeric', aggfunc = 'count')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)

...

c:\users\vdbosscj\scipy\pandas-joris\pandas\core\common.py in _astype_nansafe(ar
r, dtype, copy)
   2726
   2727         if np.isnan(arr).any():
-> 2728             raise ValueError('Cannot convert NA to integer')
   2729     elif arr.dtype == np.object_ and np.issubdtype(dtype.type, np.intege
r):
   2730         # work around NumPy brokenness, #1987

ValueError: Cannot convert NA to integer
```

**Comment by jreback** [comment] 2015-04-30 10:03
dupe of #9534

**Closed by jreback** 2015-04-30 10:03 UTC
