### ISSUE TITLE
SparseSeries error out if they're too long

### ISSUE THREAD

**Issue by cyrusmaher** [pydata/pandas#11139] opened 2015-09-18 00:50 UTC
Whether or not I can create a SparseSeries seems to depend on the length of the series:
``` python
pd.SparseSeries([1.] * 10) # works
pd.SparseSeries([1.] * 100) # error
```

I've copied the error below:
```
.../miniconda/lib/python2.7/site-packages/pandas/core/format.pyc in __init__(self, series, buf, length, header, na_rep, name, float_format, dtype, max_rows)

--> 148         self._chk_truncate()
    149 
    150     def _chk_truncate(self):

.../miniconda/lib/python2.7/site-packages/pandas/core/format.pyc in _chk_truncate(self)
    159             else:
    160                 row_num = max_rows // 2
--> 161                 series = concat((series.iloc[:row_num], series.iloc[-row_num:]))
    162             self.tr_row_num = row_num
    163         self.tr_series = series

.../miniconda/lib/python2.7/site-packages/pandas/tools/merge.pyc in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, copy)
    752                        keys=keys, levels=levels, names=names,
    753                        verify_integrity=verify_integrity,
--> 754                        copy=copy)
    755     return op.get_result()
    756     
.../miniconda/lib/python2.7/site-packages/pandas/tools/merge.pyc in __init__(self, objs, axis, join, join_axes, keys, levels, names, ignore_index, verify_integrity, copy)
803         for obj in objs:
    804             if not isinstance(obj, NDFrame):
--> 805                 raise TypeError("cannot concatenate a non-NDFrame object")
    806 
    807             # consolidate

TypeError: cannot concatenate a non-NDFrame object
```

**Comment by kawochen** [comment] 2015-09-18 01:57
This is actually a bug in `__repr__()` or `__str__()`. If you just create the `SparseSeries` in a script without printing, it will work.

**Comment by kawochen** [comment] 2015-09-18 12:01
#10560

**Comment by jreback** [comment] 2015-09-18 14:18
dupe of #10560

**Closed by jreback** 2015-09-18 14:18 UTC
