### ISSUE TITLE
to_clipboard doesn't support unicode

### ISSUE THREAD

**Issue by Winand** [pydata/pandas#11712] opened 2015-11-27 13:42 UTC
to_clipboard uses ascii encoding. And it cannot be changed.

    >>> import pandas as pd
    >>> pd.__version__
    '0.17.0'
    >>> pd.DataFrame(["Hello world"]).to_clipboard()
    >>> pd.DataFrame(["Здравствуй, мир"]).to_clipboard()
    ...
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-31: ordinal not in range(128)
    >>> pd.DataFrame(["Здравствуй, мир"]).to_clipboard(encoding="utf-8")
    ...
    TypeError: to_string() got an unexpected keyword argument 'encoding'

Had to use part of to_clipboard source, where it exports dataframe to StringIO buffer, then put it to clipboard with Qt.

**Comment by jreback** [comment] 2015-11-27 13:46
this is fixed by #9693 
if you want to give that a try and report

**Comment by jreback** [comment] 2015-11-27 13:47
pls report ``pd.show_versions()`` for the record as well.

**Comment by Winand** [comment] 2015-11-27 13:49
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en

pandas: 0.17.0
nose: 1.3.7
pip: 7.1.2
setuptools: 18.4
Cython: 0.23.4
numpy: 1.9.3
scipy: 0.16.1
statsmodels: None
IPython: 4.0.0
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.6
blosc: 1.2.8
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.5.0rc3
openpyxl: None
xlrd: 0.9.4
xlwt: None
xlsxwriter: 0.7.7
lxml: 3.4.4
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.9
pymysql: None
psycopg2: None

**Comment by Winand** [comment] 2015-11-30 05:36
Yep, updated clipboard.py works fine here.

**Comment by jreback** [comment] 2015-11-30 11:36
dupe of #9263

**Closed by jreback** 2015-11-30 11:36 UTC
Labels: Data IO, Unicode
