### ISSUE TITLE
Undesired UX behavior of DataFrame output in IPython Notebook

### ISSUE THREAD

**Issue by danieljl** [pydata/pandas#10231] opened 2015-05-29 16:50 UTC
From my previous line comment at https://github.com/pydata/pandas/commit/be80898920eab8f740cf61019327621a75d73947#commitcomment-11338872. cc @takluyver @jorisvandenbossche

Because DataFrame's `_repr_html_` returns hardcoded `div` tag with style `max-height:1000px`, if the height of DataFrame's output exceeds 1000px, it will generate a scroll bar.

First, it is unnecessary because IPython Notebook has "toggle output scrolling" feature. Second, it causes UX problem if the height of browser resolution is below 1000px (user must scroll twice: the whole page and the generated div). Third, it can't make use of "toggle output scrolling" feature (if user turn it on, it will generate nested scroll bars (worse UX)). For more detailed explanations and examples, see the steps to reproduce below.

Pandas version: 0.16.1.

Steps to reproduce:

1. Open an IPython Notebook and paste this code. It will generate an inner scroll bar because the output's height exceeds 1000px.
	```python
	import pandas as pd
	pd.DataFrame(list(range(100)))
	```

2. If you want to see all rows, first you should scroll the page.
![a](https://cloud.githubusercontent.com/assets/1947204/7887439/3ba2e788-065b-11e5-8be1-9e9cdb4eb304.png)

3. After you reach the bottom of the generated ouput's `div`, you should scroll again the inner scroll bar.
![b](https://cloud.githubusercontent.com/assets/1947204/7887460/705b87f0-065b-11e5-827c-a4c7d915e485.png)

4. If you want to toggle the IPython Notebook's "toggle output scrolling" feature, you get this.
![c](https://cloud.githubusercontent.com/assets/1947204/7887471/8620d4d2-065b-11e5-9386-8b8f08a62c07.png)

Desired behaviors:

* When "output scrolling" feature is off
![d](https://cloud.githubusercontent.com/assets/1947204/7887506/c8d131b4-065b-11e5-8936-9636094ed99b.png)

* When "output scrolling" feature is on
![e](https://cloud.githubusercontent.com/assets/1947204/7887515/d85116a4-065b-11e5-9691-7110988f95f1.png)

Solution:
Remove style property from `div` tag that DataFrame's `_repr_html_` returns.
Old: `<div style="max-height:1000px;max-width:1500px;overflow:auto;">\n`
New: `<div>\n`

Why should `max-width` be removed as well? Because it also generates *far* worse UX. If you have so many columns that the horizontal scroll bar generated, you cannot scroll it. You must refresh the page to be able to scroll it.

**Comment by shoyer** [comment] 2015-05-30 17:54
Thanks for the clear documentation of the issue with the screenshots. I agree, we should fix this.

**Comment by shoyer** [comment] 2015-05-30 17:55
Does IPython notebook cleanly handle horizontal scrolling when necessary if `max-width` is removed?

**Comment by takluyver** [comment] 2015-05-30 22:57
IIRC, in IPython 3 we put the output in its own scrollable container if it is wider than the notebook. In earlier versions, the page would just get wider, so the whole page would get a horizontal scrollbar.

**Comment by shoyer** [comment] 2015-06-03 01:18
Indeed, I verified that I get the proper horizontal scrolling behavior in IPython 3.

My only concern here is that IPython 3 may still be a little too new (3 months old) for us to change this -- we might break some folks still using earlier versions. On the other hand, upgrading IPython is pretty easy/seamless (in my experience).

Any other thoughts here?

**Comment by danieljl** [comment] 2015-06-03 06:28
@shoyer I tested using IPython 2.4.1 and pandas with `DataFrame`'s `max-width` removed. As @takluyver said, in IPython 2 the page just gets wider. Yup it is ugly, but it works. Is it acceptable?

![a](https://cloud.githubusercontent.com/assets/1947204/7953850/ddd198d8-09f3-11e5-83c8-05a51ffad9a0.png)

**Comment by shoyer** [comment] 2015-06-03 06:35
At least it only makes the one output cell wider -- it could be far worst (e.g., the entire page gets stretched).

For things like this, that work either way but are ugly for some users, I think we probably should make things nicer for users who are using the latest version of IPython. Of users who are using the latest version of pandas, a significant fraction are probably also keeping IPython up to date. So I think this change is a good idea.

**Comment by jreback** [comment] 2015-06-11 15:39
closed by #10231

**Closed by jreback** 2015-06-11 15:39 UTC
Labels: Output-Formatting

**Comment by jeremybickerstaffe** [comment] 2015-08-03 10:29
![pandas multiple scrollbars bug](https://cloud.githubusercontent.com/assets/13586102/9035712/599fab9a-39d2-11e5-9b4c-e2efc2a2930c.png)

I've encountered a bug which may be related which results in very strange scrollbar behaviour with a particular csv dataset. Unfortunately I wasn't able to generate the problem with a simple script, it occurs with the (anonymised) dataset at this link:

https://www.dropbox.com/s/gdoow6ro8u7yn70/pandas%20multiple%20scrollbars%20bug.csv?dl=0

Steps to reproduce: open a new iPython notebook and paste the following code
```
import pandas as pd
df = pd.read_csv('pandas multiple scrollbars bug.csv')
df
```

**Comment by jreback** [comment] 2015-08-03 11:14
@jeremybickerstaffe you didn't specify the ipython version. This is fixed in 0.16.2 for ipython >= 3.0.0.

**Comment by jeremybickerstaffe** [comment] 2015-08-03 12:05
My iPython is version 3.2.1

**Comment by jorisvandenbossche** [comment] 2015-08-03 12:14
I can't reproduce this with your file. Can you show the output of `pd.show_versions()`

**Comment by jeremybickerstaffe** [comment] 2015-08-03 12:20
Sure, the output is:

```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.9.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.16.2
nose: 1.3.4
Cython: 0.22
numpy: 1.9.2
scipy: 0.15.1
statsmodels: 0.6.1
IPython: 3.2.1
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.4
bottleneck: None
tables: 3.1.1
numexpr: 2.3.1
matplotlib: 1.4.3
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: 0.6.7
lxml: 3.4.2
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 0.9.9
pymysql: 0.6.6.None
psycopg2: None
```

**Comment by jorisvandenbossche** [comment] 2015-08-03 12:29
Strange, I can't reproduce it with the same version of pandas and IPython. Which browser are you using?

**Comment by jeremybickerstaffe** [comment] 2015-08-03 12:33
Chrome Version 44.0.2403.125 m (64-bit).

It does appear to be very much an edge case. I found that bizarre changes, like changing the name of the file that's being read, or changing the reading code to this below can remove the rendering problem.
```
import pandas as pd
pd.read_csv('pandas multiple scrollbars bug.csv')
```

**Comment by SoundBoySelecta** [comment] 2020-01-28 18:05
Ive had to use df.style to get scroll bars (vert/horz)
