### ISSUE TITLE
read_gbq should offer an option to save to dataset

### ISSUE THREAD

**Issue by iros** [pydata/pandas#13531] opened 2016-06-29 14:48 UTC
Right now `read_gbq` runs a query and retrieves the results into a data_frame. If one wants to also save it into a dataset table, one then has to call `to_gbq` which would stream the results back.

The `bq` command line tool has an option to pass a destination dataset table immediately on query to store the results.

```
cat queries/sample.sql | bq query --format csv 
  --destination_table=collection.table_name > output.csv
```

Ideally `read_gbq` would have an additional option like `destination_table` that could store the results immediately.

**Comment by jorisvandenbossche** [comment] 2016-06-29 19:01
cc @parthea1 @aaront @jacobschaer

**Comment by iros** [comment] 2016-06-30 14:48
It looks like the [configuration obj](https://cloud.google.com/bigquery/docs/reference/v2/jobs) for the query job here can take a `destinationTable` parameter, so we just have to carry it through: 

https://github.com/pydata/pandas/blob/f71537ab2561ab5727008095e9685966619fa7b9/pandas/io/gbq.py#L325-L331

**Comment by jreback** [comment] 2016-07-01 11:36
xref to #10474 not really sure we should support this

**Comment by jorisvandenbossche** [comment] 2016-07-07 09:13
cc @parthea

**Comment by parthea** [comment] 2016-07-07 11:37
I'm ok with closing this feature request. I'll keep PR #11209 in my back pocket in case this gets raised again. 

Looking at #11209 again, it would be cleaner to create a new api function `gbq.bqresults_to_gbq()` rather than re-define the existing `read_gbq()` which returns a DataFrame

**Comment by parthea** [comment] 2016-09-11 16:42
@jreback Can we close this as duplicate of #10474 , and continue the discussion there?

**Comment by jreback** [comment] 2016-09-11 16:48
sure

**Closed by jreback** 2016-09-11 16:48 UTC
Labels: IO Google
