### ISSUE TITLE
Panel.clip() does not work 

### ISSUE THREAD

**Issue by cbuton** [pydata/pandas#10961] opened 2015-09-01 13:52 UTC
Hello,
I tried to use the clip function on a basic Panel but it seems that the axis management is not working as expected. I believe this is an update to issue https://github.com/pydata/pandas/issues/8344

    import numpy as np
    import pandas as pd
 
    data = np.random.randn(3, 4, 5)
    panel = pd.Panel(data)
    panel.clip(0, 1)

If I run the script with pandas 0.16.2 on python 2.7.10 and 3.4.3, I'm getting the following error:

    .../pandas/core/generic.pyc in clip(self, lower, upper, out, axis)
       3052         result = self
       3053         if lower is not None:
    -> 3054             result = result.clip_lower(lower, axis)
       3055         if upper is not None:
       3056             result = result.clip_upper(upper, axis)

    .../pandas/core/generic.pyc in clip_lower(self, threshold, axis)
       3103             raise ValueError("Cannot use an NA value as a clip threshold")
       3104 
    -> 3105         subset = self.ge(threshold, axis=axis) | isnull(self)
       3106         return self.where(subset, threshold, axis=axis)
       3107 

    TypeError: f() got an unexpected keyword argument 'axis'

**Thanks a lot for all your efforts!**

**Comment by jreback** [comment] 2015-09-01 14:22
this is a duplicate of #8344

**Closed by jreback** 2015-09-01 14:22 UTC
