### ISSUE TITLE
read_csv includes the BOM of an utf8 file into the first column label

### ISSUE THREAD

**Issue by dr-leo** [pydata/pandas#13497] opened 2016-06-22 20:42 UTC
Consider the following script:

import pandas as PD

df = PD.read_csv('sample.csv',
                 encoding='utf8')
print(df.columns[:5])

**Comment by dr-leo** [comment] 2016-06-22 20:50
Attached is an utf8 or ios-8859-1 encoded csv file. It is part of IMF financial data from data.imf.org.

The following code shows that the first column label starts with the file's BOM and includes the '"' even though all other labels rightly do not contain '"' as it is the separator.

import pandas as PD

df = PD.read_csv('sample.csv',
                 encoding='utf8')
print(df.columns[:5])

The BOM is in fact prepended to the first column label even if utf8 is specified.

[sample.zip](https://github.com/pydata/pandas/files/328720/sample.zip)

**Comment by dr-leo** [comment] 2016-06-22 20:53
I should add that this bug occurs on Win7x64, Python 3.5.1, 32bit, pandas 0.18.1.

**Comment by TomAugspurger** [comment] 2016-06-22 23:49
This looks like a duplicate of https://github.com/pydata/pandas/issues/4793. Any interest in submitting a fix?

Also @dr-leo, for this to work you would need `pd.read_csv('sample.csv', encoding='utf-8-sig')`, correct?

**Closed by TomAugspurger** 2016-06-22 23:49 UTC

**Comment by dr-leo** [comment] 2016-06-23 05:16
When I use utf-8-sig, the BOM is gone, but the first column label is
'"Country Name"' instead of 'Country Name'. The others are ok though.

So I'll open a new issue. Or is there a workaround?

 

Am 23.06.2016 um 01:49 schrieb Tom Augspurger:

**Comment by jreback** [comment] 2016-06-23 05:24
this is the same exact issue as #4793

**Comment by dr-leo** [comment] 2016-06-23 08:17
Right. Tom has spotted this as well. I had only searched the open
issues for duplicates. I'll make a PR to improve the docs once I find
some time.

Using utf-8-sig uncovers another issue: Separators are not removed
from the first column Name starting right after the BOM.

Leo
