### ISSUE TITLE
ENH: Export DataFrame containing datetime with tz to HDF5 in fixed format

### ISSUE THREAD

**Issue by Tux1** [pydata/pandas#11411] opened 2015-10-22 13:00 UTC
Hello,

I noticed a bug about exporting DataFrame with columns containing localized datetime. I might be due to some another required libraries updated...
Example : 
```python 
a = pd.to_datetime(['20120201', '20130201'])
b = pd.to_datetime(['20120201', '20130201'])
dfa = pd.DataFrame([a])
dfb = pd.DataFrame([b])
dfb[0] = dfb[0].dt.tz_localize('UTC')

dfa.to_hdf('tata.hdf', 'df') # success
dfb.to_hdf('toto.hdf', 'df') # fail
```

It works fine with Series
Thanks guys

**Comment by jreback** [comment] 2015-10-22 13:03
you need to use ``format='table'``, this is not implemented for ``format='fixed'``, the default.

**Comment by Tux1** [comment] 2015-10-22 13:05
However, it was working until pandas 0.17, no ?

**Comment by jreback** [comment] 2015-10-22 13:18
It was never supported in any real way (and not tested), so it 'worked' I guess.

```
In [7]: dfb.to_hdf('toto.hdf', 'df') # fail
/Users/jreback/miniconda/envs/pandas_0.16.2/lib/python2.7/site-packages/pandas/io/pytables.py:2577: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->datetime,key->block1_values] [items->[0]]

  warnings.warn(ws, PerformanceWarning)
```

**Comment by jreback** [comment] 2015-10-22 13:21
this is a dupe of #8165 

if you'd like to work on that would be great.

**Comment by Tux1** [comment] 2015-10-22 13:23
Not very but I will try yes.
Thanks

**Comment by jreback** [comment] 2015-10-22 13:25
actually, will reopen this one and close the other

**Closed** 2015-11-17 14:57 UTC
Labels: Difficulty Intermediate, Effort Medium, IO HDF5, Timezones
