### ISSUE TITLE
pd.NaT.date() returns datetime.date(1, 255, 255)

### ISSUE THREAD

**Issue by scls19fr** [pydata/pandas#9513] opened 2015-02-18 20:19 UTC
Hello,

`pd.NaT.date()` returns `datetime.date(1, 255, 255)`
that's an odd results
I was expecting `None` (or something else) because that's really strange to have
date of year "1" in an Excel file

Kind regards

**Comment by shoyer** [comment] 2015-02-18 20:57
Could we make `NaT.date()` just raise a `ValueError`? I think I would prefer that over `None`, which would usually just mean differing the error until later.

**Comment by scls19fr** [comment] 2015-02-19 05:16
Yes raising an a `ValueError` is more understandable.

**Comment by shoyer** [comment] 2015-02-19 07:25
If you'd like to put together a PR to fix this, that would be great!

**Comment by scls19fr** [comment] 2015-02-19 09:11
Yes but where is defined `Not A Time`.
What kind of behaviour should we have ? Does getting any attribute / applying any method should raise an error ?

**Comment by shoyer** [comment] 2015-02-19 09:20
`NaT` is defined by the `NaTType` class here: https://github.com/pydata/pandas/blob/bceb342d76ca4061fc8d3a1089bc4e83a32da656/pandas/tslib.pyx#L568

NaTType is an indirect subclass of datetime, so it inherits the default `date` method. You simply need to supply the method on NaTType, e.g.,
```
def date(self):
    raise ValueError('some helpful message')
```

(and yes, this is Cython, but you write pure Python code here.)

This will also need a test to verify that the error is raised, probably somewhere around here:
https://github.com/pydata/pandas/blob/bceb342d76ca4061fc8d3a1089bc4e83a32da656/pandas/tseries/tests/test_tslib.py#L589

**Comment by shoyer** [comment] 2015-02-19 09:22
If there are other methods that are not returning appropriate values, feel free to override them to raise an error as well. But most of them should be supplying appropriate returns values already (e.g., `nan` for `NaT.year`).

**Comment by scls19fr** [comment] 2015-02-19 09:59
I directly code on GitHub and send PR this way (because I don't have a Python install here)... I just hope that Travis CI will be ok.

**Comment by scls19fr** [comment] 2015-02-19 16:54
Sorry but it seems that my PR fails with CI.

**Comment by scls19fr** [comment] 2015-02-19 17:18
PR https://github.com/pydata/pandas/pull/9523 seems ok now

**Comment by kelvin22** [comment] 2015-05-19 23:11
Probably related:

When writing the NaT to postgres using SQLAlchemy:
sqlalchemy.exc.DataError: (psycopg2.DataError) invalid input syntax for type timestamp: "0001-255-255T00:00:00"

Although I thought this was fixed a while back
https://github.com/pydata/pandas/issues/6701
https://github.com/pydata/pandas/issues/2754

**Comment by jorisvandenbossche** [comment] 2015-05-20 08:20
@kelvin22 Can you open a separate issue for this (because as you say, this should be fixed). If possible, please provide a reproducible example.

**Comment by kawochen** [comment] 2015-07-17 17:18
should be closed too?

**Closed** 2015-07-17 17:21 UTC
Labels: Error Reporting, Timeseries
