### ISSUE TITLE
Pandas: why pandas.Series.std() is quite different from numpy.std()

### ISSUE THREAD

**Issue by infozyzhang** [pydata/pandas#10489] opened 2015-07-02 06:30 UTC
I got two snippets code as follows.

>> numpy.std([766897346, 766897346, 766897346, 766897346, 766897346, 766897346, 766897346, 766897346, 766897346, 766897346])

>> 0

>> pd.Series([766897346, 766897346, 766897346, 766897346, 766897346, 766897346, 766897346, 766897346, 766897346, 766897346]).std(ddof=0)

>> 10.119288512538814

The two lists are identical but the result are quite different. I think the pandas' result must be wrong. I work on the latest version 0.16.2 with Python 3.4.

May I ask why? Is it a bug?

**Comment by shoyer** [comment] 2015-07-02 07:15
Closing this as a duplicate of #10242

Pandas uses a correct formula for the standard deviation. However, the formula we use is not as numerically stable as the formula used by numpy. Pull requests to fix this would definitely be welcome!

**Closed by shoyer** 2015-07-02 07:15 UTC
