### ISSUE TITLE
SeriesGroupBy.count() failing with TypeError

### ISSUE THREAD

**Issue by xflr6** [pydata/pandas#11101] opened 2015-09-15 08:47 UTC
```python
>>> import pandas as pd
>>> pd.__version__
u'0.17.0rc1'

>>> df = pd.DataFrame({'A': [0, 0, 1, 1], 'B': range(4)})
>>> df.groupby('A').count()['B']
A
0    2
1    2
Name: B, dtype: int64

>>> df.groupby('A')['B'].count()
Traceback (most recent call last):
...
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'
```

**Comment by jreback** [comment] 2015-09-15 10:18
dupe of https://github.com/pydata/pandas/issues/11077

fixed in master and will be in 0.17.0

thanks

**Closed by jreback** 2015-09-15 10:18 UTC
