### ISSUE TITLE
TST/BUG: integer coercion bool with int on windows

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#12850] opened 2016-04-10 16:05 UTC
xref #12841

this is a test in ```test_coercion.py, L361```

```
In [3]: import pandas as pd

In [4]: s = pd.Series([True, False, True, False])

In [5]: s.where(s,1)
Out[5]:
0    1
1    1
2    1
3    1
dtype: int32
```

on windows the scalar is not coerced to int64 (as it is on other platforms). IIRC ``.where`` already has quite complicated logic to do this. How simple is this to fix?

cc @sinhrks

**Comment by sinhrks** [comment] 2016-04-10 17:30
Maybe it is caused by ``NumPy``? I don't think everything must be fixed on ``pandas`` side, but need to clarify what the current behaviors are.

**Comment by jreback** [comment] 2016-04-10 17:32
oh it IS caused by numpy as that defaults to ``int32`` when creating integers on windows. However pandas coerces everything internally to int64. So just need to investigate if this is by a bug in the logic somewhere. Or we can just change the test. I'll take a look.

**Closed** 2016-04-10 19:09 UTC
Labels: Dtypes, Windows
