### ISSUE TITLE
API: gbq new methods naming

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#11132] opened 2015-09-17 00:19 UTC
we need to make the API's more explicit/consistent.

```
create_table
delete_table
table_exists
```

should these be
```
table_create
table_delete
table_exists
```

cc @parthea

**Comment by parthea** [comment] 2015-09-18 00:51
Can this be closed as duplicate of #11121?

**Comment by parthea** [comment] 2015-09-25 09:11
@jreback 
Can we close this one?

**Closed** 2015-09-25 09:13 UTC
Labels: Google I/O
