### ISSUE TITLE
io: to_excel leads to TypeError when index with tz

### ISSUE THREAD

**Issue by dacoex** [pydata/pandas#11961] opened 2016-01-05 10:45 UTC
I would like to save a *df* with the following *index* to an Excel file:

```dtype='datetime64[ns, Atlantic/Reykjavik]', name=u'Dates', length=4360, freq='H')
```

it shows the following error:
```
TypeError: Timestamp subtraction must have the same timezones or no timezones
```

**Comment by jorisvandenbossche** [comment] 2016-01-05 11:14
@dacoex Thanks for the report! 
I suppose this is a duplicate of https://github.com/pydata/pandas/issues/7056

This is not really implemented at the moment (excel also does not support timezones, so an implementation would something be like a removal of the timezone + warning).
For now, you can convert it to naive timestamps yourself before exporting to excel.

**Closed** 2016-01-05 11:14 UTC
Labels: Dupe, IO Excel, Timezones

**Comment by dacoex** [comment] 2016-01-05 12:26
Just as reference for anyone:
use 
```
df..tz_localize(None)
```
pandas-docs.github.io/pandas-docs-travis/timeseries.html#time-zone-handling
