### ISSUE TITLE
Series test_sum fails due to different NaN behavior

### ISSUE THREAD

**Issue by drudd** [pydata/pandas#9957] opened 2015-04-20 21:01 UTC
I have an installation of Pandas of 0.16.0 that fails TestSeries.test_sum when using Numpy 1.9.2 compiled against MKL 11.2. Here is a minimal test:

```
import numpy as np
import pandas as pd

s = np.nan*pd.util.testing.makeStringSeries()
print s.sum()
```

For Pandas 0.15.2, Numpy 1.9.1 compiled against MKL 10.3, this prints nan, but for Numpy 1.9.2 against 11.2 it prints 0.0.

I don't know whether to blame Pandas version, blas or Numpy version, and will run additional tests to distinguish which is at fault. I have stepped through execution for both cases and they are identical up to the call to <built-in function nansum> at pandas/core/nanops.py:89

**Comment by jreback** [comment] 2015-04-20 21:08
xref to #9422 and #8383

**Comment by jreback** [comment] 2015-04-20 21:09
this is a dupe of #9422  actually

feel free to comment / propose fix etc there

thanks for the report

**Closed by jreback** 2015-04-20 21:09 UTC
