### ISSUE TITLE
dataframe.columns.name attribute value is missing when dataframe.style is rendered

### ISSUE THREAD

**Issue by nmontpetit** [pydata/pandas#13305] opened 2016-05-27 18:32 UTC
The `name` attribute of `dataframe.columns` does not get populated when rendering the `dataframe.style` property of the dataframe.  This behavior occurs regardless of whether I set `styler.columns.name` explicitly.

#### Code Sample, a copy-pastable example if possible
import pandas as pd
test_df = pd.DataFrame({'A':range(4), 'B':range(4)})
test_df.columns.name = 'x_label'
test_df.index.name = 'y_label'

styler = test_df.style
styler.columns.name = 'x_label'
styler.render()

HTML output:
This is from `styler.render()`:

           <tr>
                <th class="blank">
                <th class="col_heading level0 col0">A
                <th class="col_heading level0 col1">B       
            </tr>

#### Expected Output

           <tr>
                <th class="blank">x_label
                <th class="col_heading level0 col0">A
                <th class="col_heading level0 col1">B       
            </tr>

#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0

tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0

**Comment by jreback** [comment] 2016-05-27 20:02
this is a dupe of #13266

**Closed by jreback** 2016-05-27 20:02 UTC
