### ISSUE TITLE
BUG: read_table error with tabs, dtype and index_col

### ISSUE THREAD

**Issue by brentp** [pydata/pandas#4363] opened 2013-07-25 16:06 UTC
This gist demonstrates the problem:
https://gist.github.com/brentp/6066942

It's discussed in this thread:
https://groups.google.com/forum/#!topic/pydata/hIIZpZqbY5M

As discussed in the thread, there is some interaction when specifying dtype, index_col, and sep in read_csv.

As the gist shows, things work find with sep="\s+", but fail for the same set with sep="\t" even though the file is tab-delimited.

**Comment by jreback** [comment] 2016-04-26 17:22
dupe of #9435

**Closed by jreback** 2016-04-26 17:22 UTC
Labels: Bug, CSV
