### ISSUE TITLE
BUG: read_csv causes segfault in v0.17.0

### ISSUE THREAD

**Issue by Gunthard** [pydata/pandas#11532] opened 2015-11-06 11:30 UTC
```python
>>> import pandas
>>> import StringIO
>>> pandas.read_csv(StringIO.StringIO('test\n13324234234324234322332432432'))
```

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-32-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8

pandas: 0.17.0
nose: 1.3.7
pip: 1.5.4
setuptools: 3.3
Cython: 0.23.4
numpy: 1.10.1
scipy: 0.16.1
statsmodels: None
IPython: 4.0.0
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
httplib2: 0.8
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None

**Comment by TomAugspurger** [comment] 2015-11-06 14:02
Probably a dupe of https://github.com/pydata/pandas/issues/11374, which is fixed in master (an older generated C file got in the release).

Can you checkout master and see if it fixes your problem? I'll reopen if not.

**Closed by TomAugspurger** 2015-11-06 14:02 UTC
