### ISSUE TITLE
Travis build fails on master

### ISSUE THREAD

**Issue by nbonnotte** [pydata/pandas#12240] opened 2016-02-06 07:08 UTC
https://travis-ci.org/pydata/pandas/builds/107252660

This happens since the last commit, which was merging a pull request of mine... but Travis was green for me, and beside I can't see no connection between that:

```

ERROR: test_nankurt (pandas.tests.test_nanops.TestnanopsDataFrame)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pydata/pandas/pandas/tests/test_nanops.py", line 141, in check_results
    tm.assert_almost_equal(targ, res)
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3809)
    cpdef assert_almost_equal(a, b, bint check_less_precise=False,
  File "pandas/src/testing.pyx", line 156, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2830)
    raise_assert_detail(obj, msg, a, b)
  File "/home/travis/build/pydata/pandas/pandas/util/testing.py", line 842, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Iterable are different
Second object is iterable, first isn't
[left]:  nan
[right]: [[nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/pydata/pandas/pandas/tests/test_nanops.py", line 453, in test_nankurt
    allow_str=False, allow_date=False, allow_tdelta=False)
  File "/home/travis/build/pydata/pandas/pandas/tests/test_nanops.py", line 233, in check_funs
    **kwargs)
  File "/home/travis/build/pydata/pandas/pandas/tests/test_nanops.py", line 222, in check_fun
    targarnanval, **kwargs)
  File "/home/travis/build/pydata/pandas/pandas/tests/test_nanops.py", line 184, in check_fun_data
    self.check_results(targ, res, axis)
  File "/home/travis/build/pydata/pandas/pandas/tests/test_nanops.py", line 144, in check_results
    if targ.dtype == 'm8[ns]':
AttributeError: ("'float' object has no attribute 'dtype'", 'axis: 0 of 2', 'skipna: False', 'kwargs: {}', 'testar: arr_float_nan', 'targar: arr_float', 'targarnan: arr_float_nan')
```

and my commit, which was about the formatting of float strings.

**Comment by TomAugspurger** [comment] 2016-02-06 16:24
Looks like it's a Scipy issue. Jeff has a PR here https://github.com/pydata/pandas/issues/12240.

> This happens since the last commit, which was merging a pull request of mine

Always a good feeling when your not the one who broke it!

**Comment by TomAugspurger** [comment] 2016-02-06 16:25
Ahh maybe I closed this too soon. Jeff's PR doesn't handle the nanops. Should we skip those for now (at least on Scipy 0.17)? It'd be good to get things passing again.

**Comment by jreback** [comment] 2016-02-06 16:29
yeah we should skip the failing parts for now
but of course fix them in another tissue
i think scipy fixed some bugs

**Comment by TomAugspurger** [comment] 2016-02-06 16:33
OK, I'll see if I can fix the tests. Assumed they were new bugs from scipy, not fixes.

**Comment by TomAugspurger** [comment] 2016-02-06 17:22
Oh my, these tests are complicated :) [This](https://github.com/scipy/scipy/pull/5007) is the change in scipy I believe. Still trying to work out what changed... Maybe I'll put up a PR with skipifs for now :)

**Comment by jreback** [comment] 2016-02-06 19:38
dupe of #12235

**Closed by jreback** 2016-02-06 19:38 UTC
