### ISSUE TITLE
secondary_y plot shows in separate figure

### ISSUE THREAD

**Issue by arski** [pydata/pandas#9779] opened 2015-04-01 15:43 UTC
Hi, don't know if this is my Python/some module version.. but when I try to do the following, I end up with two figures popping up, instead of the expected one:

    df[[0, 1]].plot(kind='bar', stacked=True, ylim=(0, 100))
    df[[2]].plot(secondary_y=True, color='orange', linewidth=2.0)

The data in both plots looks right, the left/right y axes are correct etc.. but they're not on the same figure :(

Also if this is of any help, if I do `fig = plt.figure()` before running the commands above, I end up with another completely empty figure shown to me first.. 

Sorry if this is something stupid and/or not caused by pandas..

**Comment by arski** [comment] 2015-04-01 16:11
Hmm, it works if I do `fig, ax = plt.subplots(1, 1)` and then add `ax=ax` to both `df.plot()` calls above.. Might be worth documenting?

However, there are two bugs now:
1. the secondary legend is on top of the first one
2. the plot width is scaled down to the line points, i.e. the first and last bars are cut off by 50%

**Comment by arski** [comment] 2015-04-01 16:13
Erm, executing the secondary_y line plot command first and the bar plot second solves issue 2. Now the plot has enough space for the bars.

**Comment by jorisvandenbossche** [comment] 2015-04-01 17:55
Another possibility is doing `ax = df[[0,1]].plot(...)` and then providing this `ax` to the second `df[[2]].plot(..)`, or by doing `df[2].plot(..)` (this is then plotting a series -> added to the existing figure). But, I think your solution of `fig, ax = plt.subplots(1, 1)` is the cleanest and clearest one.

Providing the `ax` is documented (see the docstring and http://pandas.pydata.org/pandas-docs/stable/visualization.html), but maybe not explicitly enough (see also #8776). If you have any suggestions on how to improve it, certainly welcome!

For the other questions, can you provide a small reproducible example? (some runnable code with some dummy data that shows the issue)

**Comment by arski** [comment] 2015-04-01 19:31
Hmm, the two options you mention work indeed, though somehow I'm now missing the first plot's y axis ticks/labels and the second plot's legend altogether.. Here's the snippet with the shortened version (I was doing `df[2]` before and it didn't work because my columns had titles, but otherwise that way works indeed, like the doc says!)

    from pandas import DataFrame
    import matplotlib.pyplot as plt
    
    points = [[50.69922925478467, 23.857641645143786, 2247], [51.11691211658459, 23.30982697233231, 80], [55.37656430470213, 23.25234081849125, 12]]
    keys = ['one', 'two', 'three']
    df = DataFrame(points, index=keys, columns=['OK', 'OK too', 'Where am I'])
    
    df[[0, 1]].plot(
        kind='bar',
        stacked=True,
        ylim=(0, 100),
    )
    df['Where am I'].plot(
        color='orange',
        linewidth=2.0,
        mark_right=False,
        secondary_y=True,
    )
    plt.show()

On the other hand, using the following makes the second plot's legend overlap:

    from pandas import DataFrame
    import matplotlib.pyplot as plt
    
    points = [[50.69922925478467, 23.857641645143786, 2247], [51.11691211658459, 23.30982697233231, 80], [55.37656430470213, 23.25234081849125, 12]]
    keys = ['one', 'two', 'three']
    df = DataFrame(points, index=keys, columns=['Cant see this', 'This OK', 'Move me please'])
    
    fig, ax = plt.subplots(1, 1)
    fig = df[[0, 1]].plot(
        kind='bar',
        stacked=True,
        ylim=(0, 100),
        ax=ax
    )
    fig2 = df[[2]].plot(
        color='orange',
        linewidth=2.0,
        mark_right=False,
        ax=ax,
        secondary_y=True,
    )
    plt.show()

**Comment by arski** [comment] 2015-04-01 19:32
PS. This issue has now gone almost completely off-topic.. but still some issues I think :)

**Comment by sinhrks** [comment] 2015-04-05 00:58
On first one, you should pass ``legend=True`` explicitly because it is disabled for Series by default. Then you will get the same result as latter one (overlapped legend).

The overlapped legend seems to be caused by a bug which is the same as #9610. Expected to be fixed by #9812 as below:

![9779](https://cloud.githubusercontent.com/assets/1696302/6995311/2e8f0dc6-db7a-11e4-87ce-62d51a7c7fa0.png)

**Comment by TomAugspurger** [comment] 2015-04-05 13:53
@arski should be fixed now if you're comfortable running off master. Thanks for the report.

**Closed** 2015-04-05 13:52 UTC
Labels: Visualization

**Comment by TomAugspurger** [comment] 2015-04-05 18:16
Maybe make a separate issue for that bug, if we don't have one already. You can work around it with the ax.get_xlim() methos.

**Comment by sinhrks** [comment] 2015-04-09 15:05
@arski Because `xlim` is adjusted by last plot kind, another option is draw fig2 first, then fig. Note that it should affect to legend order.
```
fig, ax = plt.subplots(1, 1)
fig2 = df[[2]].plot(
    color='orange',
    linewidth=2.0,
    mark_right=False,
    ax=ax,
    secondary_y=True,
)
fig = df[[0, 1]].plot(
    kind='bar',
    stacked=True,
    ylim=(0, 100),
    ax=ax
)
```
![figure_1](https://cloud.githubusercontent.com/assets/1696302/7069711/4cb4cefa-df15-11e4-9a05-49dbe0331e92.png)

**Comment by arski** [comment] 2015-04-09 15:21
ah, fair enough I guess, if only the legend order could be adjusted ;)
