### ISSUE TITLE
BUG: df.to_dict('record') casts ints to floats

### ISSUE THREAD

**Issue by lamyiowce** [pydata/pandas#13817] opened 2016-07-27 12:31 UTC
#### Code Sample, a copy-pastable example if possible
```
df = pd.DataFrame({"a": [1, 2], "b": [42, 65], "c": [0.5, 0.4]})
df.to_dict("records")
>>> [{'a': 1.0, 'b': 42.0, 'c': 0.5},
     {'a': 2.0, 'b': 65.0, 'c': 0.40000000000000002}]
```
#### Expected Output

```
[{'a': 1, 'b': 42, 'c': 0.5},
 {'a': 2, 'b': 65, 'c': 0.40000000000000002}]
```

#### comment
Same bug for `df.to_dict("index")` and `df.to_dict("split")`, but not for the rest. If all data is integer, the function works properly.

#### output of ``pd.show_versions()``
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-38-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: pl_PL.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 23.0.0
Cython: 0.24
numpy: 1.11.1
scipy: 0.17.1
statsmodels: 0.6.1
xarray: None
IPython: 4.2.0
sphinx: 1.4.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.0
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.2
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.40.0
pandas_datareader: None
```

**Comment by TomAugspurger** [comment] 2016-07-27 12:50
I thought we already had an issue for this, but I couldn't find it.

Looks to be somewhere around here: https://github.com/pydata/pandas/blob/31f8e4dc8af8f0d109f366d0b726aef210bf7904/pandas/core/frame.py#L897

the `.values` is casting everything to numeric. I think using `self.itertuples` would fix the problem. Would you mind checking that out, and submitting a pull request with a fix?

**Comment by TomAugspurger** [comment] 2016-07-27 13:07
Found the other issue this is a dupe of: https://github.com/pydata/pandas/issues/12859

Closing this one, you can have a look over there. Looks like we're debating whether this would be an API change, there's also a workaround there for you.

**Closed by TomAugspurger** 2016-07-27 13:07 UTC
Labels: Difficulty Novice, Dtypes, Effort Low
