### ISSUE TITLE
Sum across NaNs yields zero?

### ISSUE THREAD

**Issue by dgdillon** [pydata/pandas#11498] opened 2015-11-01 13:54 UTC
I'm running pandas 0.17.0 and was surprised by this behavior, which seems inconsistent with the docs (I expected to get NaN, not zero, at index 2). If I substitute "None" for "np.nan", I get the same result, but I get the expected result--NaN--if I use "NaT". Wondering if I've stumbled on a bug . . . 

    In [136]: df = pd.DataFrame()

    In [137]: df['a'] = [1,2,np.nan,3]

    In [138]: df['b'] = [4,5,np.nan,6]

    In [139]: df
    Out[139]: 
       a   b
    0   1   4
    1   2   5
    2 NaN NaN
    3   3   6

    In [140]: df['total'] = df.sum(axis=1)

    In [141]: df
    Out[141]: 
       a   b  total
    0   1   4      5
    1   2   5      7
    2 NaN NaN      0
    3   3   6      9

**Comment by sinhrks** [comment] 2015-11-01 14:12
Are you using ``bottleneck``? If so, dupe with #9422. 

Specify ``skipna`` for now.

```
df.sum(skipna=False)
# a   NaN
# b   NaN
# dtype: float64
```

**Comment by jreback** [comment] 2015-11-01 14:46
dupe of #9422

**Closed by jreback** 2015-11-01 14:46 UTC
Labels: Missing-data, Numeric
