### ISSUE TITLE
duplicated() performance and bug on long rows regression from 0.15.2->0.16.0

### ISSUE THREAD

**Issue by eyaler** [pydata/pandas#10161] opened 2015-05-17 14:03 UTC
the following works quickly in 0.15.2 and has a performance issue on the last operation df.T.duplicated() in 0.16.0 and 0.16.1
also on a private data set that works on 0.15.2 i get an error on 0.16.0 and 0.16.1 on the same operation.

code:

```python
import pandas,numpy

df = pandas.DataFrame({'A': [1 for x in range(1000)],
                   'B': [1 for x in range(1000)]})

print (numpy.count_nonzero(df.duplicated()))
print (numpy.count_nonzero(df.T.duplicated()))

df = pandas.DataFrame({'A': [1 for x in range(1000000)],
                   'B': [1 for x in range(1000000)]})

print (numpy.count_nonzero(df.duplicated()))
print (numpy.count_nonzero(df.T.duplicated()))


this is the error i get on the private data set (code not reproduce yet with synthetic data):
  File "C:\Anaconda3\lib\site-packages\pandas\util\decorators.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2867, in duplicated
    labels, shape = map(list, zip( * map(f, vals)))
  File "C:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2856, in f
    labels, shape = factorize(vals, size_hint=min(len(self), _SIZE_HINT_LIMIT))
  File "C:\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 135, in factorize
    labels = table.get_labels(vals, uniques, 0, na_sentinel)
  File "pandas\hashtable.pyx", line 813, in pandas.hashtable.PyObjectHashTable.get_labels (pandas\hashtable.c:14025)
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
```

**Comment by shoyer** [comment] 2015-05-18 09:14
Looks like this may be related to #9398.

@behzadnouri any ideas?

**Comment by behzadnouri** [comment] 2015-05-18 19:58
yes, https://github.com/pydata/pandas/pull/9398 will not scale well with a very wide frame; in exact same way that joining two frames on 1000000 columns will not scale well.

for `ValueError: Buffer ...` my guess is that _column names are not unique_, so when it iterates over the columns for one of the columns it gets a two dimensional array, therefore `wrong number of dimensions (expected 1, got 2)` error.

**Comment by eyaler** [comment] 2015-05-18 20:05
Thanks. column names are unique. moreover, it works when using only partial data (fewer rows) so i guess its related to the wide frame issue on the transposed data

**Comment by behzadnouri** [comment] 2015-05-18 20:13
@eyaler are you transposing the frame? if you are transposing the frame before calling into `.duplicated` then the _row_ names should be unique

**Comment by eyaler** [comment] 2015-05-18 20:20
after transposing the column names get the previous row numbers which are unique.

**Comment by jreback** [comment] 2015-06-02 20:01
@behzadnouri any thoughts on this?

**Comment by behzadnouri** [comment] 2015-06-03 21:21
@jreback i guess the easiest soln would be to switch to the old code for wide frames if no subset is selected.

**Comment by jreback** [comment] 2015-06-07 22:23
@behzadnouri that sounds ok

**Comment by jorisvandenbossche** [comment] 2015-06-08 12:24
@behzadnouri would you be able to put up a fix for this in the coming days? As this is a regression, I think we should try to include a fix in 0.16.2, to be released this friday.

**Comment by samuelclark** [comment] 2015-09-23 19:15
This issue seems to still exist, running python version 2.7.6.  On a relatively small dataframe - 5000 rows of mostly numeric data with a few date and short object columns (no duplicate columns)
```
import pandas as pd

n [14]: pd.__version__
Out[14]: '0.16.2'

In [15]: df.shape
Out[15]: (5000, 35) 

%timeit df.T.duplicated()
1 loops, best of 3: 19min 37s per loop
```

In an older version of pandas (0.12.0) on the same dataframe
```
In [13]: %timeit -n 10 dataframe.T.duplicated()
10 loops, best of 3: 23.8 ms per loop

In [14]: pd.__version__
Out[14]: ‘0.12.0’
```

For now I reimplemented the old duplicated function and am calling it separately.

*I also tested this in python version 3.4 and had the same results*

**Comment by jreback** [comment] 2015-09-23 19:56
The issue is still marked as open, though your timings are a bit odd. You might want to show ``df.info()`` on the frame you are doing.

```
In [1]: df = pd.concat([Series(np.arange(5000))]*35,axis=1)

In [2]: %timeit df.duplicated()
100 loops, best of 3: 7.97 ms per loop

In [3]: %timeit df.T.duplicated()
1 loops, best of 3: 378 ms per loop

In [4]: pd.__version__
Out[4]: '0.16.2'
```

**Comment by samuelclark** [comment] 2015-09-23 20:02
Great, here is the info from the dataframe I used
```
In [5]: df.info()
<class 'pandas.core.frame.DataFrame'>
Int64Index: 5000 entries, 0 to 4999
Data columns (total 35 columns):
...
dtypes: float64(7), int64(12), object(16)
memory usage: 1.4+ MB
```

**Comment by behzadnouri** [comment] 2015-09-23 20:20
i will patch this later today

**Comment by jreback** [comment] 2015-09-25 12:19
closed by #11180

**Closed by jreback** 2015-09-25 12:19 UTC
Labels: Difficulty Intermediate, Effort Low, Performance, Prio-medium, Regression, Reshaping

**Comment by philippschw** [comment] 2017-12-13 16:07
Issue seems to persist on extremely wide pandas DataFrame with 79 columns. Columns with same name   have been removed! 
The error is:

> ValueError: Buffer has wrong number of dimensions (expected 1, got 2)


`pd.__version__`
> '0.20.3'

**Comment by jreback** [comment] 2017-12-13 16:19
this is a long closed issue if u have a case
then open a new issue with a repro example
