### ISSUE TITLE
DataFrame.describe() no longer excludes NaN.

### ISSUE THREAD

**Issue by mikenehme** [pydata/pandas#13476] opened 2016-06-17 19:34 UTC
#### Code Sample, a copy-pastable example if possible

In 0.18.1, a single NaN in a column will cause the reported percentiles to all be NaN. In 0.18.0 and according to the documentation, NaNs are excluded.

```
import pandas as pd
import numpy as np
df = pd.DataFrame(data={'blah': range(10) + [np.nan]})
df.describe(percentiles=[0.1, 0.5, 0.9])
```
```
           blah
count  10.00000
mean    4.50000
std     3.02765
min     0.00000
10%         NaN
50%         NaN
90%         NaN
max     9.00000
```
#### Expected Output
```
           blah
count  10.00000
mean    4.50000
std     3.02765
min     0.00000
10%     0.90000
50%     4.50000
90%     8.10000
max     9.00000
```
#### output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Darwin
OS-release: 15.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 20.3
Cython: 0.23.4
numpy: 1.11.0
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext)
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None

**Comment by jreback** [comment] 2016-06-17 19:36
this is a duplicate of #13098 , closed by #13122 and will be in forthcoming 0.18.2

thanks for the report

**Closed by jreback** 2016-06-17 19:36 UTC
