### ISSUE TITLE
DOC: RangeIndex documentation missing from API

### ISSUE THREAD

**Issue by AnkurDedania** [pydata/pandas#13195] opened 2016-05-16 15:06 UTC
The only mention of the RangeIndex is on http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#range-index as of Pandas 0.18.1, should this also be mentioned within the API.

**Comment by jreback** [comment] 2016-05-16 15:10
http://pandas.pydata.org/pandas-docs/stable/advanced.html#int64index-and-rangeindex

where else do you think it needs to go specifically?

**Comment by shoyer** [comment] 2016-05-16 15:52
RangeIndex does not appear on the API docs:
http://pandas.pydata.org/pandas-docs/stable/api.html

On the other hand, neither does Int64Index, Float64Index or PeriodIndex.

I think a short section listing indexing types in the API docs would be valuable.

**Comment by jreback** [comment] 2016-05-16 16:48
this is a dupe of master issue #11962 

@AnkurDedania welcome PR's to solve pieces of that issue. (partially mentioned here)

**Closed by jreback** 2016-05-16 16:48 UTC
