### ISSUE TITLE
pandas dataframe.drop(col,axis=1) does not drop column from column.levels in multiindex dataframe

### ISSUE THREAD

**Issue by kdebrab** [pydata/pandas#12822] opened 2016-04-07 12:53 UTC
bug in pandas version 0.18.0 (long time ago seemingly same issue has been reported on [StackOverflow](http://stackoverflow.com/questions/16682190/pandas-dataframe-dropcol-axis-1-does-not-drop-column-from-column-levels-in-mul)):
```python
In[1]: import pandas as pd
  ...: import numpy as np
  ...: iterables = [['bar', 'baz', 'foo', 'qux'], ['one', 'two']]
  ...: index = pd.MultiIndex.from_product(iterables, names=['first', 'second'])
  ...: df = pd.DataFrame(np.random.randn(3, 8), index=['A', 'B', 'C'], columns=index)
  ...: df2 = df.drop('bar', axis=1)
```
At first sight, bar seems dropped from the dataframe:
```python
In[2]: df2
Out[2]: 
first        baz                 foo                 qux          
second       one       two       one       two       one       two
A      -0.625880  0.154829 -0.416494 -1.423776  0.942012 -1.495733
B      -0.704217  0.132563  1.382712 -0.123216  1.773185  1.530121
C       0.925705 -0.702249  0.113887 -0.307644  0.369242 -0.798391
```
Though not completely, as 'bar' is still listed in the columns:
```python
In[3]: df2.columns
Out[3]: 
MultiIndex(levels=[[u'bar', u'baz', u'foo', u'qux'], [u'one', u'two']],
           labels=[[1, 1, 2, 2, 3, 3], [0, 1, 0, 1, 0, 1]],
           names=[u'first', u'second'])
```

**Comment by kdebrab** [comment] 2016-04-07 12:57
I discovered issue #3686 just now...

**Comment by jreback** [comment] 2016-04-07 12:58
dupe of #2770 not a bug. you are pearing into the implementation.

**Closed by jreback** 2016-04-07 12:58 UTC

**Comment by deltaoui** [comment] 2019-04-23 10:30
@kdebrab have figured any workaround to this issue ?
