### ISSUE TITLE
read_html ignores commas

### ISSUE THREAD

**Issue by foebu** [pydata/pandas#8200] opened 2014-09-06 22:13 UTC
Hello,

I'm trying to parse a file with the extension 'xls' which is not an Excel file but it's clearly an html file (open with a text editor it's clearly html code).

One of my columns uses the italian convention of using the comma instead of the dot before decimals: 5,5 instead of 5.5. I was hoping to parse it at least as string and replace commas with dots and convert the string to a float.

The problem is that the commas are completely ignored and instead of getting 5,5 or 7,04, I'm getting 55 and 704.

Is this known? Any idea on how to solve it?

**Comment by foebu** [comment] 2015-01-18 17:28
Actually I noticed that the argument  `thousands = None` allows the parsing of the commas correctly.

**Comment by jreback** [comment] 2016-04-17 14:00
closing as dupe of #12907

**Closed by jreback** 2016-04-17 14:00 UTC
Labels: API Design, Duplicate, Enhancement, IO HTML
