### ISSUE TITLE
multiple dispatch problem when comparing pandas Series against numpy scalars

### ISSUE THREAD

**Issue by nmmarquez** [pydata/pandas#14262] opened 2016-09-20 18:01 UTC
#### Code Sample, a copy-pastable example if possible
```
import pandas as pd
import numpy as np

# this works
pd.Series([7,8,9]) >= np.int64(8)

# this doesn't 
np.int64(8) <= pd.Series([7,8,9])
```

This happens with all numpy scalar types I tested

#### Expected Output
I would expect the output should be the same regardless of the order and that neither should fail

#### output of ``pd.show_versions()``
```

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.32-573.22.1.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.1
nose: 1.3.4
pip: 8.1.2
setuptools: 23.0.0
Cython: 0.21
numpy: 1.10.2
scipy: 0.15.1
statsmodels: 0.6.1
xarray: None
IPython: 4.0.0
sphinx: 1.2.3
patsy: 0.3.0
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.4.3
openpyxl: 2.3.2
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: 0.5.7
lxml: 3.4.0
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 0.9.7
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.32.1
pandas_datareader: None
```

**Comment by jreback** [comment] 2016-09-20 18:12
this is a dupe of #13006 and fixed in 0.19.0 (0.19.0rc1 is out now)

```
In [1]: np.int64(8) <= pd.Series([7,8,9])
Out[1]:
0    False
1     True
2     True
dtype: bool

In [2]: pd.Series([7,8,9]) >= np.int64(8)
Out[2]:
0    False
1     True
2     True
dtype: bool

In [3]: pd.__version__
Out[3]: '0.19.0rc1+23.gdb9dc65'
```

**Closed by jreback** 2016-09-20 18:12 UTC
