### ISSUE TITLE
Initializing DataFrom from list of OrderedDicts does not preserve Column order

### ISSUE THREAD

**Issue by cod3monk** [pydata/pandas#13808] opened 2016-07-26 19:49 UTC
```python
>>> import pandas as pd
>>> from collections import OrderedDict
>>> od = [OrderedDict([('z', 0), ('a', 1), ('*', 2)])]
>>> pd.DataFrame(od)
   *  a  z
0  2  1  0
>>> pd.DataFrame.from_dict(od)
   *  a  z
0  2  1  0
```

If OrderedDicts are used, I would expect the column order of the first OrderDict that is encountered to be preserved, as the following:

```python
>>> pd.DataFrame(od, columns=od[0].keys())
   z  a  *
0  0  1  2
>>>
```

If different orders occur in the list, the earlier would overwrite the later. If new columns are introduced with subsequent list entries, I would expect all new columns to be appended to the original columns, with their relative order preserved.

**Comment by jreback** [comment] 2016-07-26 22:20
this is a duplicate of #https://github.com/pydata/pandas/issues/13304

which is already in master and will be in 0.19.0, see [here](https://github.com/pydata/pandas/commit/d1916404bc604ebb319710740b5dcc7eabd4fc89)

**Closed by jreback** 2016-07-26 22:20 UTC

**Comment by cod3monk** [comment] 2016-07-26 22:52
Thanks and sorry for the duplicate.
