### ISSUE TITLE
Negative interger indices lead to  IndexError: indices are out-of-bounds 

### ISSUE THREAD

**Issue by DSLituiev** [pydata/pandas#11320] opened 2015-10-14 01:01 UTC
The following test case produces `IndexError: indices are out-of-bounds` with negative integers, while positive work fine:

```
testdf = pd.DataFrame({"rna": (1.5,2.2,3.2,4.5),  -1000: [11,21,36,40],0: [10,22,43,34], 1000:[0, 10, 20, 30]})
testdf[[1000]] #this works
testdf[[-1000]] #this does not
```

**Comment by jreback** [comment] 2015-10-14 01:03
pls pd.show_versions()

**Comment by DSLituiev** [comment] 2015-10-14 01:10
just updated
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Darwin
OS-release: 14.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.0
nose: 1.3.7
pip: 7.1.2
setuptools: 18.4
Cython: 0.22.1
numpy: 1.10.1
scipy: 0.16.0
statsmodels: None
IPython: 3.2.0
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.6
blosc: None
bottleneck: 1.0.0
tables: 3.2.2.dev0
numexpr: 2.4.3
matplotlib: 1.4.3
openpyxl: 2.2.6
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.5
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
```

**Comment by jreback** [comment] 2015-10-14 01:10
dupe of https://github.com/pydata/pandas/issues/10779
which is fixed in 0.17.0

**Comment by DSLituiev** [comment] 2015-10-14 01:11
I do have 0.17.0!

**Comment by jreback** [comment] 2015-10-14 01:18
hmm ok will take a look

**Comment by jreback** [comment] 2015-10-14 10:45
yep, this is a buggie

**Closed** 2015-10-14 11:43 UTC
Labels: Bug, Difficulty Intermediate, Effort Low, Indexing
