### ISSUE TITLE
read_csv() & EOF character in string cause parsing issue

### ISSUE THREAD

**Issue by stephenjshaw** [pydata/pandas#5500] opened 2013-11-12 17:51 UTC
While importing large text files using read_csv we occasionally get an EOF (End of File ) character within a string, which causes an exception: "Error tokenizing data.  C error: EOF inside string starting at line. 844863" .  This occurs even with "error_bad_lines = False"..

Further, the line stated in the error message is not the line containing the EOF character.  In this particular case the actual row was approx. 230 rows before the one stated, which hinders exception handling.  (I now see this difference was caused by other "bad_lines" that were being skipped - the quoted error line is correct but the imported rows was less.) 

I feel it would be appropriate if "error_bad_lines = False" handled this exception and allowed such rows to be skipped.  

I note that when importing this text file into Excel, the "premature" EOF is simply ignored.

We are running on Windows 8 , with python version 2.7 and pandas version 0.12

**Comment by gfyoung** [comment] 2016-08-02 09:19
With no examples to really draw from, I created my own here for future reference, but I get no errors:
~~~python
>>> from pandas import read_csv
>>> from pandas.compat import StringIO
>>>
>>> data = 'a,b\n1\x1a,2'  # note the EOF in the middle of the last line
>>> read_csv(StringIO(data), engine='c')
    a  b
0  1  2
>>> read_csv(StringIO(data), engine='python')
    a  b
0  1  2
~~~

**Comment by gfyoung** [comment] 2016-08-22 07:23
@jreback : In light of my examples <a href="https://github.com/pydata/pandas/issues/5500#issuecomment-236850332">above</a>, IMO this is no longer an issue.  Perhaps some tests?

**Comment by jreback** [comment] 2016-08-22 13:11
yes I think your EOF or closed this
can u add that issue number here

**Closed by jreback** 2016-08-22 13:11 UTC
Labels: Bug, IO CSV

**Comment by gfyoung** [comment] 2016-08-22 14:58
IIRC I didn't do a PR for the EOF (it was the NULL char and BOM).  I can add tests though for this.

**Comment by jreback** [comment] 2016-08-22 15:04
oh right ok then

**Comment by patrickwang96** [comment] 2017-11-23 03:15
I know I'm 4 years later for this issue... but I just encounter this bug again.     
I don't think this bug is actually caused by EOF character inside a row of csv.   
To reproduce the bug,

```
In [1]: import pandas as pd

In [2]: from StringIO import StringIO

In [3]: test_csv = '"a\tb\tc\n1\t2\t3'

In [4]: pd.read_csv(test_csv, delimiter='\t')

ParserError: Error tokenizing data. C error: EOF inside string starting at line 0

In [6]: test_csv = test_csv.translate(None, '"')

In [7]: pd.read_csv(StringIO(test_csv), delimiter='\t')
Out[7]:
   a  b  c
0  1  2  3

In [8]:
```

When I was loading a large csv using pandas, the error message tells me to look for line 853, which is a totally correct line...  
The bug is actually thousands of lines behind.    

I'm on macOS 10.12.6, python2.7 annaconda build and pandas version 0.21.   This bug also exist in pandas version 0.20. Not sure about all versions before. But probably exists on all versions.

**Comment by gfyoung** [comment] 2017-11-23 03:18
@patrickwang96 : Look at your CSV string.  It's malformed with that quotation mark.  The error is to be expected.

**Comment by morganics** [comment] 2018-01-23 22:14
It's not always possible to have a perfect CSV file, so where it's more important to have a loaded data file, and less important to get all the data, then it would be good that error_bad_lines does what's expected.

**Comment by gfyoung** [comment] 2018-01-23 22:23
@morganics : It would, except that `pandas` doesn't know where the line ends and begins in this case.  You can't handle a bad line if you can't deduce where it begins or ends unfortunately.

**Comment by edrossy** [comment] 2018-09-27 16:41
I processed the same exact CSV file twice.  One time it failed and the next time it did not.  There must be some sort of race / memory condition causing this?  Fun ; -)

**Comment by gfyoung** [comment] 2018-09-29 06:44
Of the two, probably memory condition.  We don't have any concurrency for CSV parsing.  Fun, indeed 😉

**Comment by MJBee** [comment] 2018-11-06 14:17
For the reason I pointed out in my answer to this question:
https://stackoverflow.com/questions/18016037/pandas-parsererror-eof-character-when-reading-multiple-csv-files-to-hdf5/53173373#53173373
I would suggest to make the `quoting=csv.QUOTE_NONE` default instead of `csv.QUOTE_MINIMAL`.
It's easier to realise what's going on when your strings are unexpectedly parsed with quotechars then to get the error when there's odd number of quotechars or no error, but unexpected parsing for even number of quotechars.
