### ISSUE TITLE
Inconsistent results for np.isreal with strings

### ISSUE THREAD

**Issue by depristo** [pydata/pandas#10766] opened 2015-08-07 16:15 UTC
Hi Pandas.

Just uncovered a clear bug in the interaction between pandas series and numpy isreal().  The behavior is simple: isreal() produces incorrect results on panda's series that include string types.  It's not 100% clear the underlying cause but it appears to be related to np.isreal operating over the pd.Series object because isreal returns the correct result when individual elements are accessed.  See example reproducing the issue in pandas 0.16.1:

```
print(np.isreal(pd.Series(['1.0'])))
print(np.isreal(np.array(pd.Series(['1.0']))))
print(np.isreal(np.array(pd.Series(['1.0']))[0]))
print(np.isreal(np.array(pd.Series(['1.0'])[0])))
print(np.isreal(np.array(['1.0'])))
```

produces

```
[ True]
[ True]
False
False
False
```

**Comment by sinhrks** [comment] 2015-08-07 16:25
Thanks for the report, and it's ``numpy`` issue unrelated to ``pandas``

```
np.isreal(np.array(['a']))
False
```

I believe the root cause is the same as https://github.com/numpy/numpy/issues/6114

If there is a reason it should be handled in ``pandas`` side, please reopen.

**Comment by sinhrks** [comment] 2015-08-07 16:26
Ah,

**Comment by sinhrks** [comment] 2015-08-07 16:37
Hmm, numpy handle string and object dtypes differently. numpy stores string as  ``string`` dtype by default. Otherwise ``pandas`` use ``object`` dtype``

```
np.array(['1.0'])
# array(['1.0'], dtype='|S3')

np.array(pd.Series(['1.0']))
# array(['1.0'], dtype=object)
np.array(pd.Series(['1.0']))
# array(['1.0'], dtype=object)
```

And ``isreal`` returns ``True`` when the string is passed as ``object`` dtype.

```
np.isreal(np.array(['1.0'], dtype=object))
# array([ True], dtype=bool)
```

So it's clearly the numpy issue. I'll update the issue linked above. Closing as pandas side.

**Closed by sinhrks** 2015-08-07 16:37 UTC
