### ISSUE TITLE
getting IOError when creating DataFrame

### ISSUE THREAD

**Issue by gauravp2003** [pydata/pandas#9616] opened 2015-03-09 01:44 UTC
Hi

I am getting error when creating DataFrame and I have no idea on how to fix it

In [6]: import pandas.io.data as web

In [7]: import datetime

In [8]:  start = datetime.datetime(2010, 1, 1)

In [9]: end = datetime.datetime(2013, 1, 27)

In [10]: f=web.DataReader("F", 'yahoo', start, end)

In [11]: f
Out[11]: <repr(<pandas.core.frame.DataFrame at 0x7f0b9c856290>) failed: IOError: [Errno 10] No child processes>

In [12]: f.ix['2010-01-04']
Out[12]: <repr(<pandas.core.series.Series at 0x7f0b9c856150>) failed: IOError: [

**Comment by jorisvandenbossche** [comment] 2015-04-07 09:09
@gauravp2003 Thanks for reporting. Can you however report this issue again over here: https://github.com/pydata/pandas-datareader/issues (we are moving this functionality there)

Further, I cannot reproduce this issue, so can you also show the output of `pd.show_versions()`?

**Closed by jorisvandenbossche** 2015-04-07 09:09 UTC
