### ISSUE TITLE
Specify columns [indices?] to return raw HTML on read_html()?

### ISSUE THREAD

**Issue by jeremyabramson** [pydata/pandas#11921] opened 2015-12-29 06:58 UTC
As per this: http://stackoverflow.com/questions/34236870/pandas-read-html-to-return-raw-html-contents-for-certain-rows-cells-etc?noredirect=1#comment56359521_34236870 Pandas returns the HTML stripped text of tables it scrapes.  It might be nice to be able to specify columns for which you would return the raw HTML for post-processing.  This would let you maintain references to images, grab links, etc.

**Comment by jreback** [comment] 2015-12-29 19:22
this is a dupe of #10534 

we need support of passing thru & using the ``dtype`` and/or ``converters`` options.

pull-requests are welcome.

**Closed by jreback** 2015-12-29 19:22 UTC
Labels: Dtypes, Dupe, IO HTML
