### ISSUE TITLE
read_csv does not apply dtype=str correctly to NA values

### ISSUE THREAD

**Issue by alirezahkb** [pydata/pandas#10224] opened 2015-05-28 20:36 UTC
Hi,
It seems that read_csv() ignores the dtype=str when encountering NA values. For instance if the contents of file.csv is:

id,symbol
1,NA
NA,g2
3,g3
4,g4

Then df=pandas.read_csv('file.csv', dtype={'id':float, 'symbol':str}) will return the following data frame:

   id symbol
0   1    NaN
1   NaN   g2
2   3     g3
3   4     g4

which means it casts NA value in the symbol column as a float. Is this a bug or part of the read_csv design? It would make sense that when dtype=str is specified all the values will be treated as string. Note that in the above example using 'keep_default_na=False' in read_csv will cause an error.

Thanks,

**Comment by jreback** [comment] 2015-05-28 20:39
dupe of #10223

**Closed by jreback** 2015-05-28 20:39 UTC
