### ISSUE TITLE
BUG: convert_objects(convert_dates='coerce') fails on single-valued series

### ISSUE THREAD

**Issue by jmenglund** [pydata/pandas#10494] opened 2015-07-03 09:02 UTC
With an unconvertible value (like e.g. "2014-12-32"), `convert_objects(convert_dates='coerce')` is supposed to return `NaT`. When run on a series with a single unconvertible value it gives back the original string instead.

```python
>>> from pandas import Series
>>> Series(['2014-12-32']).convert_objects(convert_dates='coerce')

0    2014-12-32
dtype: object

```

#### INSTALLED VERSIONS

commit: None
python: 3.4.1.final.0
python-bits: 64
OS: Darwin
OS-release: 13.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: sv_SE.UTF-8

pandas: 0.16.2
nose: 1.3.6
Cython: None
numpy: 1.9.2
scipy: 0.15.1
statsmodels: None
IPython: 3.1.0
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.4
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.4.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: 0.6.6.None
psycopg2: None

**Comment by jreback** [comment] 2015-07-03 11:57
dupe of #9589, and fixed in #10265

**Closed by jreback** 2015-07-03 11:57 UTC
