### ISSUE TITLE
to_markdown()

### ISSUE THREAD

**Issue by libgober** [pydata/pandas#12009] opened 2016-01-10 13:20 UTC
Trying to share some tables produced in pandas with a coauthor over email.  Would be great if I could export to markdown from a pandas dataframe so that I could just copy the text into the email and use toggle.  Probably there's other use cases for markdown style table output.

**Comment by TomAugspurger** [comment] 2016-01-10 13:46
Dupe of https://github.com/pydata/pandas/issues/11052

We recently added Jinja as an optional dependency, so this shouldn't be terribly difficult to do, but no one has gotten around to it yet. Feel free to claim it if you want!

**Closed by TomAugspurger** 2016-01-10 13:46 UTC
