### ISSUE TITLE
Support for json lines format

### ISSUE THREAD

**Issue by MaxNoe** [pydata/pandas#12212] opened 2016-02-02 22:29 UTC
This is a useful format for streamed applications. 

It's basically the records orientation without the brackets and commas after each line.

http://jsonlines.org

**Comment by jreback** [comment] 2016-02-02 22:34
this is a dupe of #9180

**Closed by jreback** 2016-02-02 22:34 UTC
Labels: Duplicate, IO JSON

**Comment by jreback** [comment] 2016-02-02 22:37
pull-requests are always welcome!
