### ISSUE TITLE
How to select content store in the Panel using 'item' index

### ISSUE THREAD

**Issue by Fredericxian** [pydata/pandas#12819] opened 2016-04-07 07:10 UTC
#### wp
Out[50]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 55640 (major_axis) x 9 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 55639
Minor_axis axis: TradingDay to AskVolume1

store.select('wp','items>0')
Traceback (most recent call last):

  File "<ipython-input-51-79d40b638607>", line 1, in <module>
    store.select('wp','items>0')

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 680, in select
    return it.get_result()

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 1364, in get_result
    results = self.func(self.start, self.stop, where)

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 673, in func
    columns=columns, **kwargs)

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 3671, in read
    if not self.read_axes(where=where, **kwargs):

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 3222, in read_axes
    self.selection = Selection(self, where=where, **kwargs)

  File "C:\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 4584, in __init__
    self.condition, self.filter = self.terms.evaluate()

  File "C:\Anaconda3\lib\site-packages\pandas\computation\pytables.py", line 586, in evaluate
    self.filter = self.terms.prune(FilterBinOp)

  File "C:\Anaconda3\lib\site-packages\pandas\computation\pytables.py", line 117, in prune
    res = pr(left.value, right.value)

  File "C:\Anaconda3\lib\site-packages\pandas\computation\pytables.py", line 112, in pr
    encoding=self.encoding).evaluate()

  File "C:\Anaconda3\lib\site-packages\pandas\computation\pytables.py", line 276, in evaluate
    self)

  File "C:\Anaconda3\lib\site-packages\pandas\core\base.py", line 42, in __str__
    return self.__unicode__()

  File "C:\Anaconda3\lib\site-packages\pandas\computation\pytables.py", line 228, in __unicode__
    "[{1}]".format(self.filter[0], self.filter[1]))

TypeError: 'NoneType' object is not subscriptable

if I use item==0, it can be selected successfully.

store.select('wp','items==0')
Out[52]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 1 (items) x 55640 (major_axis) x 9 (minor_axis)
Items axis: 0 to 0
Major_axis axis: 0 to 55639
Minor_axis axis: AskPrice1 to UpdateTime

#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 8.1
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: zh_CN

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: None
xarray: None
IPython: 4.0.3
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.5.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.11
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0

**Comment by jreback** [comment] 2016-04-07 13:02
dupe of #12820

**Closed by jreback** 2016-04-07 13:02 UTC
