### ISSUE TITLE
timedelta from string requires leading 0

### ISSUE THREAD

**Issue by hayd** [pydata/pandas#9851] opened 2015-04-11 05:08 UTC
http://stackoverflow.com/questions/29573441/calculate-difference-between-times-rows-in-dataframe-pandas#comment47297436_29573471

```
In [11]: pd.to_timedelta("06:40:00")
Out[11]: Timedelta('0 days 06:40:00')

In [12]: pd.to_timedelta("6:40:00")
ValueError: cannot create timedelta string converter for [6:40:00]
```

**Comment by jreback** [comment] 2015-04-11 13:06
dupe of #9570

**Closed by jreback** 2015-04-11 13:06 UTC
