### ISSUE TITLE
Plot expressions

### ISSUE THREAD

**Issue by wiso** [pydata/pandas#13537] opened 2016-06-30 14:01 UTC
It would be nice to have the possibility to plot expressions. Suppose I have a dataframe with three columns: col1, col2, col3. Now I can do:

    df.plot.scatter(x='col1', y='col2')

it would be nice to be able to plot expressions directly:

   df.plot.scatter(x='col1 ** 2', y = 'col2 / sqrt(col3)')

and also for other plotting methods (e.g. histograms)

**Comment by TomAugspurger** [comment] 2016-07-01 02:24
This is a duplicate of https://github.com/pydata/pandas/pull/12168, which we passed on at the time.

Since you are the second person to request it though, perhaps it's worth a second look. Feel free to post over there with additional use-cases / why this would be worth implementing 👍

**Closed by TomAugspurger** 2016-07-01 02:25 UTC

**Comment by wiso** [comment] 2016-07-01 06:19
I am coming from [ROOT](root.cern.ch) where this feature is very common with [TTree::Draw](https://root.cern.ch/doc/master/classTTree.html#a73450649dc6e54b5b94516c468523e45). In physics this is very common. Suppose I have a three columns with the position of a point ('x', 'y', 'z') and one with the the time, I want to plot the distance from the origin:

    df.plot.scatter(x='time', y='sqrt(x**2 + y**2 + z**2)')
