### ISSUE TITLE
Timestamp constructor parses ISO 8601 incorrectly near DST boundaries

### ISSUE THREAD

**Issue by ischwabacher** [pydata/pandas#8225] opened 2014-09-09 18:29 UTC
Original post, edited to correct ISO 8601 formats.  The originally titled bug does not exist.  There is, however, some unexpected behavior:

> It looks like short-form ISO 8601 parsing uses the right sign after all:
> ```python
> In [1]: import pandas as pd
>
> In [2]: t = pd.Timestamp('2013-11-03 1:30:00', tz='America/Havana')
>
> In [3]: t.strftime('%Y-%m-%d %H:%M:%S %Z %z')
> Out[3]: '2013-11-03 01:30:00 CST -0500'
>
> In [4]: t.strftime('%Y%m%dT%H%M%S%z')   # ISO 8601 short format
> Out[4]: '20131103T013000-0500'
>
> In [5]: pd.Timestamp(t.strftime('%Y%m%dT%H%M%S%z'))
> Out[5]: Timestamp('2013-11-03 01:30:00-0500', tz='tzoffset(None, -18000)')
>
> In [6]: t == _
> Out[6]: True   # Not a bug after all!
>
> In [7]: t.strftime('%Y-%m-%dT%H:%M:%S%z')   # ISO 8601 long format
> Out[7]: '2013-11-03T01:30:00-0500'
>
> In [8]: pd.Timestamp(t.strftime('%Y-%m-%dT%H:%M:%S%z'))
> Out[8]: Timestamp('2013-11-03 01:30:00-0500', tz='pytz.FixedOffset(-300)')   # why pytz?
>
> In [9]: t == _
> Out[9]: True
>
> In [10]: t.strftime('%Y%m%dT%H%M%SZ%z')   # Not a real ISO 8601 format (note the 'Z')
> Out[10]: '20131103T013000Z-0500'
>
> In [11]: pd.Timestamp(t.strftime('%Y%m%dT%H%M%SZ%z'))
> Out[11]: Timestamp('2013-11-03 01:30:00+0500', tz='tzoffset(None, 18000)')
> # This is the behavior that inspired the bug report.  I don't know if this is a valid parse
> # or not, but it sure is unexpected.
> ```
> It would be awfully embarrassing if I filed a bug report because I couldn't read ISO 8601...

However, in the process of investigating this issue, I encountered the following, which is definitely a bug:

```python
In [12]: ts = ['2013-11-%s3 %s1:30:00' % (x, y) for x in ['', '0'] for y in ['', '0']]

In [13]: ts
Out[13]: 
['2013-11-3 1:30:00',
 '2013-11-3 01:30:00',
 '2013-11-03 1:30:00',
 '2013-11-03 01:30:00']   # only this one is ISO 8601

In [14]: tzs = ['America/%s' % s for s in ['Chicago', 'New_York', 'Havana']]

In [15]: [[pd.Timestamp(t, tz=tz) for t in ts] for tz in tzs]
Out[15]: 
[[Timestamp('2013-11-03 01:30:00-0600', tz='America/Chicago'),
  Timestamp('2013-11-03 01:30:00-0600', tz='America/Chicago'),
  Timestamp('2013-11-03 01:30:00-0600', tz='America/Chicago'),
  Timestamp('2013-11-03 01:30:00-0500', tz='America/Chicago')],   # DST
 [Timestamp('2013-11-03 01:30:00-0500', tz='America/New_York'),
  Timestamp('2013-11-03 01:30:00-0500', tz='America/New_York'),
  Timestamp('2013-11-03 01:30:00-0500', tz='America/New_York'),
  Timestamp('2013-11-03 01:30:00-0400', tz='America/New_York')],   # DST
 [Timestamp('2013-11-03 01:30:00-0500', tz='America/Havana'),
  Timestamp('2013-11-03 01:30:00-0500', tz='America/Havana'),
  Timestamp('2013-11-03 01:30:00-0500', tz='America/Havana'),
  Timestamp('2013-11-03 00:30:00-0500', tz='America/Havana')]]   # Just plain wrong
```

I'm not sure what's going on here.

**Comment by adamgreenhall** [comment] 2015-03-31 18:05
this is still a problem, seems to alter hours between 2 and 6 on spring forward and hours between 2 and 5 on fall back:

    In [1]: import pandas as pd
    In [2]: print pd.__version__
    0.16.0
    In [3]: for hr in range(8):
        print hr
        for date in ['2015-01-01', '2015-03-08', '2015-11-01']:
            print pd.Timestamp('{} 0{}:00:00'.format(date, hr), tz='US/Eastern')

    0
    2015-01-01 00:00:00-05:00
    2015-03-08 00:00:00-05:00
    2015-11-01 00:00:00-04:00
    1
    2015-01-01 01:00:00-05:00
    2015-03-08 01:00:00-05:00
    2015-11-01 01:00:00-04:00
    2
    2015-01-01 02:00:00-05:00
    2015-03-08 03:00:00-04:00
    2015-11-01 01:00:00-05:00
    3
    2015-01-01 03:00:00-05:00
    2015-03-08 04:00:00-04:00
    2015-11-01 02:00:00-05:00
    4
    2015-01-01 04:00:00-05:00
    2015-03-08 05:00:00-04:00
    2015-11-01 03:00:00-05:00
    5
    2015-01-01 05:00:00-05:00
    2015-03-08 06:00:00-04:00
    2015-11-01 04:00:00-05:00
    6
    2015-01-01 06:00:00-05:00
    2015-03-08 07:00:00-04:00
    2015-11-01 06:00:00-05:00
    7
    2015-01-01 07:00:00-05:00
    2015-03-08 07:00:00-04:00
    2015-11-01 07:00:00-05:00

**Comment by ischwabacher** [comment] 2015-03-31 18:09
Oh, I totally forgot about this.  I did bisect it and found the commit with the bug, but I never found the bug itself.  At the very least I will post the SHA-1 when I have a moment.

**Comment by ischwabacher** [comment] 2015-10-30 14:50
...and I forgot to do this. The problem is in 67323069fb5e8f1de3000d7606d26172a2e18a9f, presumably somewhere in [parse_iso_8601_datetime](https://github.com/pydata/pandas/blob/67323069fb5e8f1de3000d7606d26172a2e18a9f/pandas/src/datetime/np_datetime_strings.c#L382), which is a horrible function. Why on earth would you handle "now" and "today" in your ISO8601 parsing code? Whyyy?

**Comment by jreback** [comment] 2015-10-30 14:57
closing as is dupe of #11481 (simpler discussion :)

**Comment by jreback** [comment] 2015-10-30 14:58
@ischwabacher yeh, the parsing should actually be before, though this DOES make it much faster I suspect.

**Closed by jreback** 2015-10-30 14:58 UTC
Labels: Timezones
