### ISSUE TITLE
to_datetime does not handle timezones correctly for timestamps

### ISSUE THREAD

**Issue by CodeSturgeon** [pydata/pandas#9341] opened 2015-01-22 23:09 UTC
It seems that the `to_datetime` function always assumes that a timestamp is in local time and converts it to UTC. This does not seem to be the case with converting from strings.

This code:
```python
from datetime import datetime
import time
import pandas as pd
now = datetime.now()
ts = time.mktime(now.timetuple())
print ts
print now.strftime('%Y-%m-%d %H:%M')
print pd.to_datetime(ts, unit='s')
print pd.to_datetime(ts, unit='s', utc=True)
print pd.to_datetime(now.strftime('%Y-%m-%d %H:%M'))
```

Give this result (pandas 0.15.1):
```
1421967906.0
2015-01-22 18:05
2015-01-22 23:05:06
2015-01-22 23:05:06+00:00
2015-01-22 18:05:00
```

Note that when `to_datetime` is converting a timestamp five hours are added no matter the `utc=` arg value.

**Comment by jreback** [comment] 2015-01-22 23:16
thanks for reporting
this is a dupe of #6415 pull requests are welcome

**Closed by jreback** 2015-01-22 23:16 UTC
