### ISSUE TITLE
ENH: add a "name" field to DataFrame, consistent with Series

### ISSUE THREAD

**Issue by mangecoeur** [pydata/pandas#9223] opened 2015-01-10 15:57 UTC
It would be logical to add a `name` field to DataFrame, similar to Series. Then when you construct a Panel it can try to use the `name`, in the same way as when you construct a DataFrame from Series.

It would also be useful when loading/saving DataFrames to files and DBs, for example at the moment to save to HDF you always have to add a key and for SQL a table name, it would be logical to attach these to the DataFrame itself as its name parameter.

**Comment by jreback** [comment] 2015-01-10 16:02
dupe of #447 

long discussed. It IS possible, just would have to be done carefully.

The primary argument against have a DataFrame having named attributes that propogate is kind of moot for this simple type of attribute, which could be propogated similarly to the Series.name attribute.

**Closed by jreback** 2015-01-10 16:02 UTC
