### ISSUE TITLE
multiple test failures in version 0.17.0/1 and python3.5

### ISSUE THREAD

**Issue by jlec** [pydata/pandas#11687] opened 2015-11-24 11:14 UTC
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.3.0-lh-nvidia
machine: x86_64
processor: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
byteorder: little
LC_ALL: None
LANG: en_GB.utf8

pandas: 0.17.1
nose: 1.3.7
pip: 7.1.2
setuptools: 18.5
Cython: 0.23.4
numpy: 1.10.1
scipy: 0.16.1
statsmodels: 0.6.1
IPython: 4.0.0
sphinx: 1.3.1
patsy: 0.4.1
dateutil: 2.4.2
pytz: 2015.7
blosc: 1.2.8
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.5.0
openpyxl: None
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.7
lxml: None
bs4: 4.4.1
html5lib: 0.9999999
httplib2: 0.9.2
apiclient: None
sqlalchemy: 1.0.9
pymysql: 0.6.7.None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
Jinja2: None
```

```python
======================================================================
FAIL: test_legacy_write_frame (pandas.io.tests.test_sql.TestSQLApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/io/tests/test_sql.py", line 589, in test_legacy_write_frame
    flavor='sqlite')
  File "/usr/lib64/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/util/testing.py", line 2060, in assert_produces_warning
    % extra_warnings)
AssertionError: Caused unexpected warning(s): ['PendingDeprecationWarning'].

======================================================================
FAIL: test_not_reflect_all_tables (pandas.io.tests.test_sql.TestSQLApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/io/tests/test_sql.py", line 913, in test_not_reflect_all_tables
    self.assertEqual(len(w), 0, "Warning triggered for other table")
AssertionError: 2 != 0 : Warning triggered for other table

======================================================================
FAIL: test_timedelta (pandas.io.tests.test_sql.TestSQLApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/io/tests/test_sql.py", line 673, in test_timedelta
    df.to_sql('test_timedelta', self.conn)
  File "/usr/lib64/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/util/testing.py", line 2060, in assert_produces_warning
    % extra_warnings)
AssertionError: Caused unexpected warning(s): ['PendingDeprecationWarning'].

======================================================================
FAIL: test_warning_case_insensitive_table_name (pandas.io.tests.test_sql.TestSQLApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/io/tests/test_sql.py", line 926, in test_warning_case_insensitive_table_name
    self.assertEqual(len(w), 0, "Warning triggered for writing a table")
AssertionError: 1 != 0 : Warning triggered for writing a table

======================================================================
FAIL: test_legacy_write_frame (pandas.io.tests.test_sql.TestSQLApiConn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/io/tests/test_sql.py", line 589, in test_legacy_write_frame
    flavor='sqlite')
  File "/usr/lib64/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/util/testing.py", line 2060, in assert_produces_warning
    % extra_warnings)
AssertionError: Caused unexpected warning(s): ['PendingDeprecationWarning'].

======================================================================
FAIL: test_not_reflect_all_tables (pandas.io.tests.test_sql.TestSQLApiConn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/io/tests/test_sql.py", line 913, in test_not_reflect_all_tables
    self.assertEqual(len(w), 0, "Warning triggered for other table")
AssertionError: 2 != 0 : Warning triggered for other table

======================================================================
FAIL: test_timedelta (pandas.io.tests.test_sql.TestSQLApiConn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/io/tests/test_sql.py", line 673, in test_timedelta
    df.to_sql('test_timedelta', self.conn)
  File "/usr/lib64/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/util/testing.py", line 2060, in assert_produces_warning
    % extra_warnings)
AssertionError: Caused unexpected warning(s): ['PendingDeprecationWarning'].

======================================================================
FAIL: test_warning_case_insensitive_table_name (pandas.io.tests.test_sql.TestSQLApiConn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/io/tests/test_sql.py", line 926, in test_warning_case_insensitive_table_name
    self.assertEqual(len(w), 0, "Warning triggered for writing a table")
AssertionError: 1 != 0 : Warning triggered for writing a table

======================================================================
FAIL: test_bigint_warning (pandas.io.tests.test_sql.TestSQLiteAlchemy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/io/tests/test_sql.py", line 1666, in test_bigint_warning
    self.assertEqual(len(w), 0, "Warning triggered for other table")
AssertionError: 2 != 0 : Warning triggered for other table

======================================================================
FAIL: test_bigint_warning (pandas.io.tests.test_sql.TestSQLiteAlchemyConn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.17.1/work/pandas-0.17.1-python3_5/lib/pandas/io/tests/test_sql.py", line 1666, in test_bigint_warning
    self.assertEqual(len(w), 0, "Warning triggered for other table")
AssertionError: 2 != 0 : Warning triggered for other table

----------------------------------------------------------------------
```

**Comment by agrapentin** [comment] 2015-12-06 04:19
```console
[andrew@localhost ~]$ which python
~/local/Python35/bin/python
```
```console
[andrew@localhost ~]$ python --version
Python 3.5.1rc1
```
```console
[andrew@localhost ~]$ pip list
beautifulsoup4 (4.4.1)
Bottleneck (1.0.0)
cairocffi (0.7.2)
cffi (1.3.1)
cycler (0.9.0)
Cython (0.23.4)
decorator (4.0.4)
et-xmlfile (1.0.1)
html5lib (0.9999999)
httplib2 (0.9.2)
jdcal (1.2)
Jinja2 (2.8)
jsonschema (2.5.1)
MarkupSafe (0.23)
matplotlib (1.5.0)
mistune (0.7.1)
nbconvert (4.1.0)
nbformat (4.0.1)
nose (1.3.7)
notebook (4.0.6)
numexpr (2.4.6)
numpy (1.10.2rc1)
openpyxl (2.3.1)
pandas (0.17.1)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.5)
pip (7.1.2)
ptyprocess (0.5)
pycparser (2.14)
Pygments (2.0.2)
pygobject (3.18.2)
pyparsing (2.0.6)
python-dateutil (2.4.2)
pytz (2015.7)
pyzmq (15.1.0)
qtconsole (4.1.1)
readline (6.2.4.1)
scipy (0.16.1)
setuptools (18.2)
simplegeneric (0.8.1)
six (1.10.0)
SQLAlchemy (1.0.9)
tables (3.2.2)
terminado (0.5)
tornado (4.3)
traitlets (4.0.0)
xlrd (0.9.4)
XlsxWriter (0.7.7)
xlwt (1.0.0)

```


```console
======================================================================
FAIL: test_legacy_write_frame (pandas.io.tests.test_sql.TestSQLApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/io/tests/test_sql.py", line 589, in test_legacy_write_frame
    flavor='sqlite')
  File "/home/andrew/local/Python35/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/util/testing.py", line 2060, in assert_produces_warning
    % extra_warnings)
AssertionError: Caused unexpected warning(s): ['PendingDeprecationWarning'].

======================================================================
FAIL: test_not_reflect_all_tables (pandas.io.tests.test_sql.TestSQLApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/io/tests/test_sql.py", line 913, in test_not_reflect_all_tables
    self.assertEqual(len(w), 0, "Warning triggered for other table")
AssertionError: 2 != 0 : Warning triggered for other table

======================================================================
FAIL: test_timedelta (pandas.io.tests.test_sql.TestSQLApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/io/tests/test_sql.py", line 673, in test_timedelta
    df.to_sql('test_timedelta', self.conn)
  File "/home/andrew/local/Python35/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/util/testing.py", line 2060, in assert_produces_warning
    % extra_warnings)
AssertionError: Caused unexpected warning(s): ['PendingDeprecationWarning'].

======================================================================
FAIL: test_warning_case_insensitive_table_name (pandas.io.tests.test_sql.TestSQLApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/io/tests/test_sql.py", line 926, in test_warning_case_insensitive_table_name
    self.assertEqual(len(w), 0, "Warning triggered for writing a table")
AssertionError: 1 != 0 : Warning triggered for writing a table

======================================================================
FAIL: test_legacy_write_frame (pandas.io.tests.test_sql.TestSQLApiConn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/io/tests/test_sql.py", line 589, in test_legacy_write_frame
    flavor='sqlite')
  File "/home/andrew/local/Python35/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/util/testing.py", line 2060, in assert_produces_warning
    % extra_warnings)
AssertionError: Caused unexpected warning(s): ['PendingDeprecationWarning'].

======================================================================
FAIL: test_not_reflect_all_tables (pandas.io.tests.test_sql.TestSQLApiConn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/io/tests/test_sql.py", line 913, in test_not_reflect_all_tables
    self.assertEqual(len(w), 0, "Warning triggered for other table")
AssertionError: 2 != 0 : Warning triggered for other table

======================================================================
FAIL: test_timedelta (pandas.io.tests.test_sql.TestSQLApiConn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/io/tests/test_sql.py", line 673, in test_timedelta
    df.to_sql('test_timedelta', self.conn)
  File "/home/andrew/local/Python35/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/util/testing.py", line 2060, in assert_produces_warning
    % extra_warnings)
AssertionError: Caused unexpected warning(s): ['PendingDeprecationWarning'].

======================================================================
FAIL: test_warning_case_insensitive_table_name (pandas.io.tests.test_sql.TestSQLApiConn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/io/tests/test_sql.py", line 926, in test_warning_case_insensitive_table_name
    self.assertEqual(len(w), 0, "Warning triggered for writing a table")
AssertionError: 1 != 0 : Warning triggered for writing a table

======================================================================
FAIL: test_bigint_warning (pandas.io.tests.test_sql.TestSQLiteAlchemy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/io/tests/test_sql.py", line 1666, in test_bigint_warning
    self.assertEqual(len(w), 0, "Warning triggered for other table")
AssertionError: 2 != 0 : Warning triggered for other table

======================================================================
FAIL: test_bigint_warning (pandas.io.tests.test_sql.TestSQLiteAlchemyConn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrew/local/Python35/lib/python3.5/site-packages/pandas/io/tests/test_sql.py", line 1666, in test_bigint_warning
    self.assertEqual(len(w), 0, "Warning triggered for other table")
AssertionError: 2 != 0 : Warning triggered for other table

----------------------------------------------------------------------
Ran 9077 tests in 1219.977s

FAILED (SKIP=152, failures=10)

```

**Comment by jreback** [comment] 2015-12-06 04:23
dupe of #11112 

certainly willing to take a pr to fix

**Closed by jreback** 2015-12-06 04:23 UTC
