### ISSUE TITLE
Memory error when plotting simple time series

### ISSUE THREAD

**Issue by andreabedini** [pydata/pandas#10650] opened 2015-07-22 03:07 UTC
This crashes:

```
import pandas as pd
index = pd.timedelta_range(start="06:00:01", end="12:00:00", freq='S')
pd.Series(range(index.size), index=index).plot()
```

Traceback at https://gist.github.com/andreabedini/074d529ff63356312ce6

So far I have figured out that `_get_default_locs` gets called with completely bogus `vmin` an `vmax`.

**Comment by jreback** [comment] 2015-07-22 10:36
dupe of #8711

**Closed by jreback** 2015-07-22 10:36 UTC

**Comment by andreabedini** [comment] 2015-07-22 11:30
Thanks @jreback
