### ISSUE TITLE
DOC: Is sort preserved inside groupby?

### ISSUE THREAD

**Issue by nickeubank** [pydata/pandas#9651] opened 2015-03-13 21:11 UTC
Empirically, it seems to be the case that if one sorts a dataframe then takes a groupby, that sort is preserved within each groupby group. For example, it seems to be the case that `my_func` below always gets a df sorted by age. But I can't find any documentation on whether this is guaranteed, so I'm currently re-sorting data in `my_func` to be safe. 

    df.sort(columns = ['users', 'age'], inplace = True)
    df.groupby('users').apply(my_func)

Does anyone know if this is a guaranteed behavior, and if so, might it be worth adding to docs?

This is particularly relevant for the `groupby().nth()` command, since if sort isn't preserved, it's not clear what it grabs!

**Comment by jreback** [comment] 2015-03-13 21:31
dupe of #8588 

sort is preserved, but this really needs some validation tests specifically for this (there are of tests that would fail if this is not the case, but we a specific tests for this).

Feel free to submit a pr / docs for this.

**Closed by jreback** 2015-03-13 21:31 UTC

**Comment by nickeubank** [comment] 2015-03-13 21:35
Thanks! Will keep an eye on this -- have a conference coming up, so can't commit just yet, but will address later if still up.
