### ISSUE TITLE
Pandas returns 0/y=inf, even when y is a non-zero dataframe or series.

### ISSUE THREAD

**Issue by JohnNapier** [pydata/pandas#9286] opened 2015-01-17 17:54 UTC
Pandas returns the wrong result for the operation **0/y** where **y** is a dataframe or series of non-zero values:

```python
import pandas as pd
y=pd.Series(range(1,10))
print 0/y # wrong
```

However, this operation would work:

```python
for i in y:print 0/i # correct
```

I'm using Pandas 0.15.2-1.

**Comment by jreback** [comment] 2015-01-17 18:01
this is a dupe of #8445 

a pull-request to fix is welcome

**Closed** 2015-01-17 18:01 UTC
Labels: Bug, Numeric

**Comment by JohnNapier** [comment] 2015-01-17 18:58
@keszybz, @jreback, I don't think this is a dupe. In the other issue, the answer should be NaN. In this issue, the answer should be zero. Do you agree?

**Comment by jreback** [comment] 2015-01-17 19:01
It exactly the same causation. A bug in fill_zeros; I cross referenced this, to make this a tests as well.

**Comment by JohnNapier** [comment] 2015-01-17 19:04
@jreback, adding as a test is good. Thanks.

**Comment by jreback** [comment] 2015-01-17 19:06
pull-requests are welcome!

This actually is a very straightforward (meaning I think I put a pointer to exactly where it should be changed). The logic is just off in a case I think.

hint hint hint :)
