### ISSUE TITLE
adding new row to frame breaks types

### ISSUE THREAD

**Issue by behzadnouri** [pydata/pandas#9269] opened 2015-01-16 12:30 UTC
xref https://github.com/pydata/pandas/issues/8596

    >>> df
       a
    0  1
    >>> df.dtypes
    a    int64
    dtype: object
    >>> df.loc[1, 'a'] = 2
    >>> df
       a
    0  1
    1  2
    >>> df.dtypes
    a    float64
    dtype: object

in an intermediate step `nan` is inserted, and the data are casted to floats

**Comment by jreback** [comment] 2015-01-16 12:33
type conversion is not done here. as it *can* be expensive. imagine doing this repeatedly (not recommended anyhow).

This is a side-effect of this type of enlargement. a user can use ``concat`` if they want type preservation. However, you *can* fix the impl to avoid the 2-step creation with missing then filling. 

Is that the intention here? as an enhnacement?

**Comment by behzadnouri** [comment] 2015-01-16 14:09
agreed that a code change to handle this should not be expensive in terms of performance cost; added the issue just because https://github.com/pydata/pandas/issues/8596 is a _similar_ issue, so there _may_ be a solution which works for both cases.

**Comment by goretkin** [comment] 2016-09-30 19:16
can `concat` guarantee that the new row is added in-place?

**Comment by shoyer** [comment] 2016-09-30 20:31
> can concat guarantee that the new row is added in-place?

concat *never* updates in-place.

**Comment by jorisvandenbossche** [comment] 2016-09-30 20:42
This actually seems a duplicate of https://github.com/pydata/pandas/issues/6485 (BUG/ENH: dtype change on enlargement).

**Closed by jorisvandenbossche** 2016-09-30 20:42 UTC
Labels: Dtypes, Enhancement, Missing-data
