### ISSUE TITLE
Dataframe diff unexpected result

### ISSUE THREAD

**Issue by kdebrab** [pydata/pandas#11996] opened 2016-01-08 11:06 UTC
Pandas version 0.17.1:

```python
In [1]: import pandas as pd
   ...: data = pd.DataFrame({'d':[1,2,3],'e':[1.5,2,3],'f':[2,2,3]},index=list('abc'))
   ...: data.diff(axis=1)
Out[1]: 
    d   e  f
a NaN NaN  1
b NaN NaN  0
c NaN NaN  0
```
Hint: the following gives expected result
```python
In [2]: data.astype(float).diff(axis=1)
Out[2]: 
    d    e    f
a NaN  0.5  0.5
b NaN  0.0  0.0
c NaN  0.0  0.0
```

**Comment by TomAugspurger** [comment] 2016-01-08 13:02
This seems similar to https://github.com/pydata/pandas/pull/10930

[This](https://github.com/pydata/pandas/pull/10930#issuecomment-139319613) comment suggests that the fix there won't work for mixed dtypes (but you only have ints)

**Comment by jreback** [comment] 2016-01-08 13:44
this is a dupe of #10539

**Closed by jreback** 2016-01-08 13:44 UTC
Labels: Bug, Numeric
