### ISSUE TITLE
pd.DataFrame.astype should allow dict as argument

### ISSUE THREAD

**Issue by MaxNoe** [pydata/pandas#12801] opened 2016-04-05 14:57 UTC
Currently `pd.DataFrame.astype` only allows for one type.

I would like it to support a `dict` mapping column names to dtypes. 
Like for example the `dtype` argument of `pd.read_json`.
```python
df = pd.DataFrame({'a': [1, 2, 3], 'b': [1, 2, 3]})
df = df.astype({'a': 'int16', 'b': 'float32'})
```

**Comment by jreback** [comment] 2016-04-05 15:03
dupe of #12081 

thanks. there is a PR is progress IIRC. welcome to have you pick it up.

**Closed by jreback** 2016-04-05 15:03 UTC
